DefangLabs/defang

src/pkg/github/auth.go
Remove var that only makes sense server-side.
=> Remove max login length

src/cmd/cli/main.go, src/pkg/cli/compose.go, src/pkg/cli/composeDown.go, src/pkg/cli/composeRestart.go, src/pkg/cli/composeStart.go, src/pkg/cli/compose_test.go, src/pkg/cli/connect.go
=> Load project from docker compose file once

src/cmd/cli/color.go, src/cmd/cli/main.go, src/pkg/cli/client/byoc.go, src/pkg/cli/client/byoc_test.go, src/pkg/cli/client/client.go, src/pkg/cli/client/grpc.go, src/pkg/cli/client/provider.go, src/pkg/cli/client/provider_test.go, src/pkg/cli/compose.go, src/pkg/cli/composeDown.go, src/pkg/cli/composeRestart.go, src/pkg/cli/composeStart.go, src/pkg/cli/composeStop.go, src/pkg/cli/delete.go, src/pkg/cli/teardown.go
=> cli: add teardown command

src/cmd/cli/main.go, src/pkg/cli/client/byoc.go
needs https://github.com/defang-io/defang-mvp/pull/511
=> cli: add cd cancel and list subcommands

src/cmd/cli/main.go, src/pkg/cli/connect.go
=> Get the tenantID before load compose file

src/pkg/aws/ecs/cfn/setup.go, src/pkg/aws/ecs/info.go, src/pkg/cmd/info.go, src/pkg/cmd/run.go, src/pkg/docker/info.go, src/pkg/local/local.go, src/pkg/local/local_test.go, src/pkg/types/driver.go
I added this for running Pulumi on the local (dev) machine. Might be over-engineered.
=> crun: local process driver

src/pkg/cli/tail.go
=> tail: hide fabric status messages

src/cmd/cli/main.go, src/pkg/cli/client/grpc.go
=> cli: handle multiple deletes

samples/golang/AWS S3/compose.yaml, samples/golang/Basic Service/compose.yaml, samples/golang/ChatGPT API/compose.yaml, samples/golang/ChatGPT API/main.go, samples/golang/Fetch and Return JSON/compose.yaml, samples/golang/Fetch and Return JSON/main.go, samples/golang/Web Page and Form Post/compose.yaml, samples/nodejs/AWS S3/compose.yaml, samples/nodejs/Basic Service/compose.yaml, samples/nodejs/ChatGPT API/compose.yaml, samples/nodejs/Fetch and Return JSON/compose.yaml, samples/nodejs/Web Page and Form Post/compose.yaml, samples/nodejs/chat/compose.yaml, samples/nodejs/chat/docker-compose.yml, samples/nodejs/minimal/docker-compose.yml, samples/other/imgproxy/docker-compose.yml, samples/other/vllm/docker-compose.yml, samples/python/AI-ML Music/Dockerfile, samples/python/AI-ML Music/compose.yaml, samples/python/AWS S3/Dockerfile, samples/python/AWS S3/compose.yaml, samples/python/Basic Service/Dockerfile, samples/python/Basic Service/compose.yaml, samples/python/ChatGPT API/Dockerfile, samples/python/ChatGPT API/compose.yaml, samples/python/Fetch and Return JSON/Dockerfile, samples/python/Fetch and Return JSON/compose.yaml, samples/python/Web Page and Form Post/Dockerfile, samples/python/Web Page and Form Post/compose.yaml
=> Add memory reservation and health check to samples

src/cmd/cli/main.go, src/pkg/cli/agree_tos.go, src/pkg/cli/login.go, src/pkg/github/auth.go
=> cli: show terms on first use

src/pkg/cli/client/byoc.go, src/pkg/cli/client/byoc_integration_test.go, src/pkg/cli/client/byoc_test.go
fixes defang-io/defang-mvp/issues/515
=> Add project to endpoint and FQDN if it is available

src/cmd/cli/main.go, src/pkg/cli/client/byoc.go, src/pkg/cli/compose.go, src/pkg/cli/compose_test.go, src/pkg/cli/connect.go
remove warning about CNAME lookup failure
fixes #177
=> Override project name for Saas when loading compose file

src/cmd/cli/main.go
login fallback would not show interactive ToS prompt
=> fix: login logic

src/cmd/cli/main.go
=> fix: make -n --name optional

src/cmd/cli/main.go, src/pkg/cli/colorizer.go, src/pkg/cli/tail.go
=> feat: add emphasis to help

src/cmd/cli/main.go, src/pkg/cli/connect.go
=> fix: remove extra output from shell completion script

src/pkg/cli/compose.go, src/pkg/cli/composeStart.go, src/pkg/cli/composeStart_test.go, src/tests/testproj/Dockerfile, src/tests/testproj/compose.yaml
Support `target`: https://github.com/compose-spec/compose-spec/blob/master/build.md#target
=> feat: support build target

README.md, src/cmd/cli/main.go, src/pkg/cli/compose.go, src/pkg/cli/connect.go
same as https://docs.docker.com/compose/environment-variables/envvars/#compose_project_name
=> feat: add COMPOSE_PROJECT_NAME override

samples/golang/AWS S3/compose.yaml, samples/golang/Basic Service/compose.yaml, samples/golang/ChatGPT API/compose.yaml, samples/golang/Fetch and Return JSON/compose.yaml, samples/golang/Web Page and Form Post/compose.yaml, samples/nodejs/AWS S3/compose.yaml, samples/nodejs/Basic Service/compose.yaml, samples/nodejs/ChatGPT API/compose.yaml, samples/nodejs/Fetch and Return JSON/compose.yaml, samples/nodejs/Web Page and Form Post/compose.yaml, samples/nodejs/chat/compose.yaml, samples/nodejs/minimal/compose.yaml, samples/nodejs/nextjs/compose.yml, samples/other/imgproxy/compose.yaml, samples/other/vllm/compose.yaml, samples/python/AI-ML Music/compose.yaml, samples/python/AWS S3/compose.yaml, samples/python/Basic Service/compose.yaml, samples/python/ChatGPT API/compose.yaml, samples/python/Fetch and Return JSON/compose.yaml, samples/python/Web Page and Form Post/compose.yaml, src/pkg/cli/composeStart.go, src/tests/noprojname/compose.yaml, src/tests/secretname/compose.yaml, src/tests/testproj/compose.yaml
=> cli: warn on unsupported restart

src/cmd/cli/main.go
=> cli: usage for commands with args

src/cmd/cli/main.go, src/cmd/cli/track.go, src/pkg/cli/connect.go
Fixes https://github.com/defang-io/defang-mvp/issues/556
=> Track correct provider

samples/golang/slackbot/Dockerfile, samples/golang/slackbot/README.md, samples/golang/slackbot/compose.yaml, samples/golang/slackbot/go.mod, samples/golang/slackbot/go.sum, samples/golang/slackbot/main.go
Figured I might as well take my learnings from my attempts and turn them into a sample. If someone better versed in Go could take a look at this and make sure I'm not making any silly mistakes that would be helpful.
=> Slackbot Sample

src/pkg/cli/client/byoc/clouds/aws.go, src/pkg/clouds/aws/ecs/logs.go, src/pkg/clouds/aws/ecs/tail.go
=> Support --since for BYOC

README.md, src/pkg/cli/tail.go
alternative to #258, ref: https://github.com/defang-io/defang/issues/251
=> fix: use timezone from TZ env

src/cmd/crun/main.go
and only process env for run command
=> Parse flag set differently based on command

src/cmd/cli/command/version_test.go, src/pkg/cli/client/byoc/clouds/aws.go, src/pkg/cli/client/byoc/clouds/byoc_integration_test.go, src/pkg/cli/client/byoc/clouds/stream.go, src/pkg/cli/composeStart_test.go, src/pkg/cli/compose_test.go, src/pkg/cli/tail.go, src/pkg/clouds/aws/ecs/cfn/setup_test.go, src/pkg/clouds/aws/ecs/logs.go, src/pkg/clouds/aws/secrets_test.go, src/pkg/docker/run_test.go, src/pkg/github/id_token_test.go, src/pkg/local/local_test.go
Based on #284 (merge that one first)
=> Fix tail cancel

src/pkg/cli/client/grpc.go
Client side for https://github.com/defang-io/defang-mvp/pull/616
=> Use Deploy rpc

src/Makefile, src/cmd/cli/command/commands.go, src/pkg/cli/agree_tos.go, src/pkg/cli/client/client.go, src/pkg/cli/client/grpc.go, src/pkg/cli/generate.go
requires JIT agreement to terms.
Fixes #293
=> allow generate without login

flake.nix, src/go.mod, src/go.sum, src/pkg/cli/client/byoc/clouds/aws.go, src/pkg/cli/client/client.go, src/pkg/cli/client/grpc.go, src/pkg/cli/client/mock.go, src/pkg/cli/compose.go, src/pkg/cli/composeStart.go, src/pkg/cli/composeStart_test.go, src/pkg/cli/tail.go, src/tests/fixupenv/compose.yaml
=> Fixup service names in env vars

src/cmd/cli/command/commands.go, src/cmd/cli/command/version.go, src/cmd/cli/command/version_test.go, src/cmd/cli/main.go, src/cmd/cli/version.go, src/cmd/gendocs/main.go, src/pkg/term/unbuf_windows.go
=> Fix CLI version

src/pkg/cli/tail.go, src/pkg/github/auth.go
=> Handle Ctrl-C on Windows

src/pkg/cli/cert.go
remove unnecessary errors.Join check
lowercase the alb dns to be added to r53
=> Add spinner to trigger step

src/cmd/cli/command/commands.go, src/pkg/cli/client/byoc/clouds/aws.go, src/pkg/cli/client/client.go, src/pkg/cli/client/grpc.go, src/pkg/cli/composeRestart.go, src/pkg/cli/restart.go, src/pkg/cli/whoami.go, src/tests/empty/compose.yaml
=> cli: better feedback

src/cmd/cli/command/commands.go, src/pkg/cli/client/grpc.go, src/pkg/cli/client/state.go, src/pkg/cli/client/state_test.go, src/pkg/cli/login.go
=> fix state file on windows

src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/cli/client/byoc/aws/byoc_integration_test.go, src/pkg/cli/client/byoc/aws/byoc_test.go, src/pkg/cli/client/byoc/aws/common.go, src/pkg/cli/client/byoc/aws/stream.go, src/pkg/cli/client/byoc/clouds/aws.go, src/pkg/cli/connect.go
* make a package per cloud (not one `clouds` package)
* make file with `ByocAws` match the names of the test files
=> rename BYOC package

src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/cli/client/client.go, src/pkg/cli/client/grpc.go, src/pkg/cli/composeDown.go, src/pkg/cli/composeRestart.go, src/pkg/cli/composeStop.go, src/pkg/cli/delete.go, src/pkg/cli/restart.go, src/pkg/types/etag.go
=> move ETag to its own package

src/Makefile, src/cmd/cli/command/commands.go, src/pkg/cli/teardown.go
Add `--force` to teardown when services are running. Workaround for #358
=> Improve cd teardown command

pkgs/defang/cli.nix, src/.goreleaser.yml
=> Set up shell completions in installers

src/bin/install
=> install shell completions

src/cmd/cli/command/commands.go, src/cmd/cli/command/track.go, src/cmd/cli/version.go, src/pkg/cli/client/grpc.go
=> optimize completion

src/bin/install
also keeping vars to minimum to avoid polluting the user's shell
=> fixes for bash

.github/workflows/install.yml, src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/cli/tail.go
Got a Go warning about possible leaked ctx.
=> Cancel ctx (go warning)

src/cmd/cli/command/commands.go, src/pkg/cli/client/grpc.go
Implement code to call DeleteSecrets on the backend when deleting config values.
=> Implement use of DeleteSecrets cli call.

src/pkg/cli/client/grpc.go
=> use connect.NewRequest

src/pkg/cli/cert.go
And modify the log message to highlight what user should change.
=> Query the NS servers of the domain until insync for cert gen DNS check

src/pkg/cli/client/playground.go, src/pkg/cli/client/playground_test.go
Fix a panic in playground when not authenticated
=> fix a panic in playground

src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/cli/client/byoc/aws/byoc_integration_test.go, src/pkg/cli/client/byoc/aws/byoc_test.go, src/pkg/cli/client/byoc/baseclient.go, src/pkg/cli/client/byoc/do/byoc.go, src/pkg/cli/client/grpc.go, src/pkg/cli/connect.go
Integration tests were broken after DO refactoring
=> fix byoc integration test

src/pkg/cli/tail.go, src/pkg/cli/tail_test.go, src/pkg/term/colorizer.go, src/pkg/term/colorizer_test.go, src/pkg/utils.go
=> fix pulumi dot

src/cmd/cli/command/commands.go, src/pkg/cli/client/playground.go, src/pkg/clouds/aws/ecs/cfn/setup.go
Make it harder to manually delete CD stack in AWS console
=> Enable termination protection for CD stack

src/cmd/cli/command/commands.go, src/pkg/cli/composeStart.go
=> Support reading config from file

src/cmd/cli/command/commands.go, src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/cli/client/playground.go, src/pkg/clouds/aws/ecs/cfn/setup.go, src/pkg/clouds/aws/ecs/cfn/template.go
=> reuse cd bucket

src/pkg/clouds/aws/ecs/cfn/outputs/ids.go, src/pkg/clouds/aws/ecs/cfn/setup.go, src/pkg/clouds/aws/ecs/cfn/template.go
=> Check template revision before updates

src/pkg/cli/loader.go, src/pkg/cli/loader_test.go, src/tests/alttestproj/compose.yaml.golden, src/tests/compose-go-warn/compose.yaml.golden, src/tests/empty/compose.yaml.golden, src/tests/fixupenv/compose.yaml.golden, src/tests/noprojname/compose.yaml.golden, src/tests/profiles/compose.yaml, src/tests/profiles/compose.yaml.golden, src/tests/redis/compose.yaml.golden, src/tests/secretname/compose.yaml.golden, src/tests/static-files/compose.yaml.golden, src/tests/testproj/.dockerignore, src/tests/testproj/compose.yaml.golden
Always set profile `defang` during loading of Compose files. Added tests.
=> set profile defang

src/pkg/cli/tail.go
=> better colors for white background light theme

src/pkg/cli/composeStart.go, src/tests/emptyenv/Dockerfile, src/tests/emptyenv/compose.yaml, src/tests/emptyenv/compose.yaml.golden
=> feat: ignore local shell env

src/pkg/github/auth.go
* opening the browser with old tab (old "state" query param) would close the channel and write to it.
=> fix(login): panic

src/cmd/cli/command/commands.go, src/cmd/cli/command/deploymentinfo.go, src/pkg/cli/agree_tos.go, src/pkg/cli/cert.go, src/pkg/cli/compose.go, src/pkg/cli/composeStart.go, src/pkg/cli/connect.go, src/pkg/cli/generate.go, src/pkg/cli/init.go, src/pkg/cli/login.go, src/pkg/cli/tail.go, src/pkg/cli/whoami.go, src/pkg/github/auth.go, src/pkg/term/colorizer.go, src/pkg/term/colorizer_test.go
Ensure prefix is still needed to prevent adding prefix to empty lines
=> Fix space for term.warn and remove -*! from the logging as it would be added automatically

src/cmd/cli/command/commands.go
=> changed the naming convention of generate and new for CLI

src/pkg/cli/client/playground.go, src/pkg/term/colorizer.go
Fix term.Error space regression
=> Fix restart command with project support

src/cmd/cli/command/commands.go, src/pkg/cli/bootstrap.go, src/pkg/cli/cert.go, src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/cli/client/byoc/baseclient.go, src/pkg/cli/client/byoc/do/byoc.go, src/pkg/cli/client/client.go, src/pkg/cli/client/mock.go, src/pkg/cli/client/playground.go, src/pkg/cli/composeDown.go, src/pkg/cli/configDelete.go, src/pkg/cli/configList.go, src/pkg/cli/configSet.go, src/pkg/cli/getServices.go, src/pkg/cli/loader.go, src/pkg/cli/tail.go, src/pkg/types/error.go
=> Load project name from remote when not in a compose folder

.github/workflows/build-samples-json.yml, .github/workflows/go.yml, src/.goreleaser.yml
=> add winget

src/pkg/cli/client/byoc/aws/byoc_integration_test.go, src/pkg/cli/client/mock.go, src/pkg/cli/composeStart.go, src/pkg/cli/composeStart_test.go, src/tests/configoverride/compose.yaml, src/tests/configoverride/compose.yaml.golden
=> Override env by config

.github/workflows/go.yml, src/pkg/cli/cert_test.go, src/pkg/dns/resolver.go, src/pkg/dns/resolver_test.go, src/pkg/term/colorizer_windows.go
Fix for CI build error https://github.com/DefangLabs/defang/actions/runs/9649163986/job/26612024321#step:6:51
=> Fix windows build

src/pkg/cli/compose/convert.go, src/tests/platforms/compose.yaml, src/tests/platforms/compose.yaml.convert, src/tests/platforms/compose.yaml.golden, src/tests/platforms/compose.yaml.warnings
=> support x86_64 platform

src/pkg/cli/bootstrap.go, src/pkg/cli/cert.go, src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/cli/composeDown.go, src/pkg/cli/configDelete.go, src/pkg/cli/configList.go, src/pkg/cli/configSet.go, src/pkg/cli/getServices.go, src/pkg/cli/tail.go, src/tests/sanity/compose.yaml.convert, src/tests/sanity/compose.yaml.golden, src/tests/sanity/compose.yaml.warnings
Better fix for MVP CI failure https://github.com/DefangLabs/defang-mvp/actions/runs/9653599270/job/26626547585#step:6:46 (that test should not have to set `COMPOSE_PROJECT_NAME` at all)
=> make project optional for CD

src/cmd/cli/command/commands.go, src/pkg/cli/new.go, src/pkg/cli/new_test.go
Currently when trying to create a project from an non-existent sample it asks for project name and opens vscode but no files are created.
Closes #483
=> Nonexistent project error fix

README.md, src/cmd/cli/command/track.go, src/pkg/cli/client/grpc.go, src/pkg/cli/client/playground.go, src/pkg/cli/client/playground_test.go, src/pkg/cli/connect.go, src/pkg/cli/new.go, src/pkg/cli/new_test.go
CLI would hang without internet, Ctrl-C wouldn't break:
* Remove last occurrence of `context.TODO`
* Fixed `new` unit test when Wi-Fi is down
=> move WhoAmI out of Connect

.github/workflows/go.yml, src/Makefile, src/README.md
=> Release target in Makefile

src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/cli/client/byoc/aws/byoc_integration_test.go, src/pkg/cli/client/byoc/do/byoc.go, src/pkg/cli/client/client.go, src/pkg/cli/client/mock.go, src/pkg/cli/client/playground.go, src/pkg/cli/tail.go
Fix for misnomer, related to #459
=> rename Tail to Follow in CLI

src/cmd/cli/command/commands.go
Fixes the bug @raphaeltm saw where the AI-debugger is canceled because the passed-in ctx was canceled.
=> fix: debug was using canceled ctx

.github/workflows/go.yml
Address release actions issues.
=> fix release gha

src/cmd/cli/command/commands.go, src/pkg/cli/compose/validation.go, src/pkg/cli/debug.go, src/pkg/cli/generate.go, src/pkg/cli/new.go, src/pkg/types/error.go
Specifically for users that don't know Docker Compose or Dockerfile.
Fixes #585
=> add more help info to the CLI

src/cmd/cli/command/commands.go
Add `--env` / `-e` to set a config's value from the environment. 
```sh
export ASDF=123
defang config set -e ASDF #ok
defang config set -e ASDF file #error
defang config set -e ASDF=1234 #error
```
See also #598
=> Set config from env

src/bin/install
=> Allow user to specify install version in env var

src/pkg/cli/client/byoc/aws/byoc.go
Show pending operations in `defang cd ls`. We don't currently have a way to clean these up, but at least we're not hiding stacks that could potentially have resources in your AWS account.
=> show pending operations in cd ls

src/tests/compose-go-warn/compose.yaml.warnings, src/tests/configoverride/compose.yaml.warnings, src/tests/debugproj/compose.yaml.warnings, src/tests/emptyenv/compose.yaml.warnings, src/tests/fixupenv/compose.yaml.warnings, src/tests/healthcheck/compose.yaml.warnings, src/tests/networks/compose.yaml.warnings, src/tests/platforms/compose.yaml.warnings, src/tests/postgres/compose.yaml.warnings, src/tests/profiles/compose.yaml.warnings, src/tests/redis/compose.yaml.warnings, src/tests/secretname/compose.yaml.warnings, src/tests/static-files/compose.yaml.warnings, src/tests/toomany/compose.yaml.warnings, src/tests/toomany/docker-compose.yml.warnings
=> Fix validation test, update expected warnings

src/cmd/cli/command/commands.go
=> Fix defang ls

src/cmd/cli/command/commands_test.go
because it's trying to connect to fabric
=> Move the version test out of the 'short' group 

src/cmd/cli/command/compose.go, src/pkg/cli/client/client.go, src/pkg/cli/composeDown.go, src/pkg/cli/composeRestart.go, src/pkg/cli/composeStop.go, src/pkg/cli/delete.go, src/pkg/cli/restart.go
Part of #180. See also https://github.com/DefangLabs/defang-mvp/issues/594
=> Support for optional service names on down

src/pkg/cli/cert.go, src/pkg/dns/resolver.go
Do not print out http body content in debug log
Fixes: #637 #644
=> Create a transport that use root resolver instead of normal resolver

src/pkg/cli/client/byoc/aws/byoc.go
Small improvement that fell out of https://github.com/DefangLabs/defang/issues/668
This doesn't resolve that issue, but it does make the scope of current and future error messages more understandable.
=> Prefix service validation error with service name

src/pkg/cli/cert.go, src/pkg/dns/resolver.go, src/pkg/dns/resolver_integration_test.go
For https://github.com/DefangLabs/defang-mvp/issues/981
=> Handle multiple CNAME resolve and debug log http redirect

src/pkg/scope/scope.go
for GDPR https://github.com/DefangLabs/defang-mvp/issues/991
=> Add delete scope

src/pkg/cli/compose/context.go, src/tests/alttestproj/compose.yaml.warnings, src/tests/debugproj/compose.yaml.warnings, src/tests/emptyenv/compose.yaml.warnings, src/tests/secretname/compose.yaml.warnings, src/tests/testproj/compose.yaml.warnings
fixes #68 
updating text in CLI so it is more informative for the user
=> Changed compressing/building build context messages to be simpler

src/pkg/cli/compose/loader.go, src/tests/interpolate/compose.yaml, src/tests/interpolate/compose.yaml.convert, src/tests/interpolate/compose.yaml.golden, src/tests/interpolate/compose.yaml.warnings
=> Leave interpolation for CD

src/pkg/cli/client/byoc/aws/stream.go, src/pkg/logs/fluent.go
For use in https://github.com/DefangLabs/defang-mvp/pull/1091
=> Clean up some log types

src/pkg/cli/compose/convert.go
Show a warning in the CLI to avoid the error from https://github.com/DefangLabs/defang-mvp/pull/1031
=> No managed redis/db on Playground

src/pkg/clouds/do/appPlatform/setup.go, src/pkg/clouds/do/appPlatform/setup_test.go
…to avoid killing the job while it's still running
=> Extend CD grace period to 10min

src/pkg/cli/compose/convert.go, src/tests/fixupenv/compose.yaml.warnings
fixes #596 
Updated some config error text. Open to suggestions to be even more clear.
=> update text, hopefully a little clearer

src/pkg/cli/cert.go, src/pkg/cli/tail.go, src/pkg/spinner/spinner.go
fixes #602 
Spinner currently is tied to main thread timing which may cause sporadic spinner animation (or none at all).
=> show spinner via goroutine

src/cmd/cli/command/compose.go, src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/cli/client/byoc/aws/stream.go, src/pkg/cli/client/byoc/aws/subscribe.go, src/pkg/cli/client/byoc/baseclient.go, src/pkg/cli/client/byoc/do/byoc.go, src/pkg/cli/tail.go, src/pkg/cli/upgrade.go, src/pkg/clouds/aws/ecs/cfn/setup.go, src/pkg/clouds/aws/ecs/cfn/waiter.go, src/pkg/clouds/aws/ecs/logs.go, src/pkg/clouds/aws/ecs/run.go, src/pkg/clouds/aws/route53.go, src/pkg/clouds/aws/route53_test.go
=> Use Route53 delegation ID for BYOC on AWS

.github/workflows/go.yml
Using ideas from:
https://goreleaser.com/blog/nightly-actions/#dont-forget-to-clean-up
https://goreleaser.com/customization/nightlies/
Using the default nightly version tags
=> Add nightly build to github workflow

.github/workflows/go.yml
=> Revert "Add nightly build to github workflow"

src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/cli/client/byoc/do/byoc.go
The compose as-is changes were made (merged) for AWS but not for DO.
=> Compose as-is fixes for DO

src/pkg/cli/compose/validation.go, src/pkg/cli/compose/validation_test.go, src/pkg/cli/composeUp.go
Fix for #794 `context.Background()`
=> Remove a context.Background

src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/quota/service.go, src/pkg/quota/service_test.go
Pre-requisite for https://github.com/DefangLabs/defang-mvp/pull/1176
We only want to recommend using BYOC as a solution if the error is quota-related. If the error is just an unacceptable config, then using BYOC won't help and promoting it is only a distraction.
=> Partition quota and config validation

Makefile, src/pkg/cli/composeDown.go, src/pkg/clouds/aws/ecs/ecsserviceaction/aws_event.go, src/pkg/clouds/aws/ecs/ecsserviceaction/ecs_service_action.go, src/pkg/clouds/aws/ecs/ecsserviceaction/marshaller.go, src/pkg/clouds/aws/ecs/ecstaskstatechange/attachment_details_details.go, src/pkg/clouds/aws/ecs/ecstaskstatechange/attributes_details.go, src/pkg/clouds/aws/ecs/ecstaskstatechange/aws_event.go, src/pkg/clouds/aws/ecs/ecstaskstatechange/container_details.go, src/pkg/clouds/aws/ecs/ecstaskstatechange/ecs_task_state_change.go, src/pkg/clouds/aws/ecs/ecstaskstatechange/marshaller.go, src/pkg/clouds/aws/ecs/ecstaskstatechange/network_binding_details.go, src/pkg/clouds/aws/ecs/ecstaskstatechange/network_interface_details.go, src/pkg/clouds/aws/ecs/ecstaskstatechange/overrides.go, src/pkg/clouds/aws/ecs/ecstaskstatechange/overrides_item.go
Run `go fmt` with pre-commit hook.
Setup with `make setup` in the root working directory.
=> Run go fmt with pre-commit hook

src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/cli/client/byoc/do/byoc.go
This is a regression from #523 
We don't really want to be using this pb struct any longer, https://github.com/DefangLabs/defang-mvp/issues/1184 offers a longer-term solution
=> fix printEndpoints

src/pkg/clouds/aws/secrets.go
Next Tokens were not being taken into account, sometimes the parameters are on the next page.
=> update to request more parameters if given a next token

src/pkg/clouds/do/appPlatform/parse.go, src/pkg/clouds/do/appPlatform/parse_test.go
in alignment with https://github.com/DefangLabs/defang-mvp/pull/1223
=> remove auth from image regexp

src/pkg/cli/client/byoc/do/byoc.go
If CD fails, `up` would run forever, because we didn't check the deployment failure cases.
=> Handle CD failures on DO

src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/cli/client/byoc/do/byoc.go, src/pkg/cli/compose/load_content.go, src/pkg/cli/compose/load_content_test.go
Add fallback param for use in MVP repo.
=> Copy LoadFromContent from MVP

src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/cli/client/byoc/do/byoc.go, src/pkg/cli/compose/load_content.go, src/pkg/cli/compose/load_content_test.go
Reverts DefangLabs/defang#838 for now so I can cut a release..
=> Revert "Copy LoadFromContent from MVP"

src/pkg/cli/composeUp.go
Fixes the issue with samples CI failing because `defang compose config` fails if there's configs being used in the sample. `compose config` is the same as `compose up --dry-run` and we shouldn't care whether configs are actually set.
=> Skip config validation in dry-run

pkgs/defang/cli.nix, src/go.mod, src/go.sum, src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/cli/client/byoc/aws/validation.go, src/pkg/cli/client/byoc/aws/validation_test.go
Detect and error out `defang compose up` when compose.yaml requests for GPU's out of range [1-8].
https://github.com/DefangLabs/defang-mvp/issues/741
=> add GPU validation for range of GPU amounts

src/pkg/cli/client/byoc/aws/validation.go
Show better error message when no quota is set for user and how they can resolve it
https://github.com/DefangLabs/defang-mvp/issues/741
=> Eric update gpu error text

src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/cli/client/byoc/baseclient.go
Reference to hardcoded quota values breaking deployment.
=> fix reference to hardcoded quotas

src/cmd/cli/command/commands.go, src/cmd/cli/command/compose.go, src/cmd/cli/command/hint.go, src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/cli/client/byoc/aws/byoc_test.go, src/pkg/cli/client/byoc/baseclient.go, src/pkg/cli/client/byoc/do/byoc.go, src/pkg/cli/client/grpc.go, src/pkg/cli/client/playground.go, src/pkg/cli/client/playground_test.go, src/pkg/cli/compose/compose_test.go, src/pkg/cli/connect.go, src/pkg/cli/token.go, src/pkg/clouds/aws/ecs/upload.go, src/pkg/clouds/do/appPlatform/setup.go, src/pkg/types/tenant.go
* add `--org` flag
Like `--cluster org@` but that one's hidden for us only.
=> Rename TenantID to TenantName

src/cmd/cli/command/commands.go, src/pkg/cli/bootstrap.go, src/pkg/cli/client/projectName.go, src/pkg/cli/composeDown.go, src/pkg/cli/configDelete.go, src/pkg/cli/configList.go, src/pkg/cli/configSet.go, src/pkg/cli/delete.go, src/pkg/cli/getServices.go, src/pkg/cli/tail.go
* fixes 'defang ps' w/o compose file
=> Use LoadProjectNameWithFallback

src/cmd/cli/command/commands.go, src/pkg/cli/getServices.go, src/pkg/cli/getServices_test.go
=> Hack for fixing cd ls

src/cmd/cli/command/cd.go, src/cmd/cli/command/commands.go, src/cmd/cli/command/compose.go, src/pkg/cli/agree_tos.go, src/pkg/cli/client/byoc/aws/byoc.go
Require auth (and hide commands) according to https://www.notion.so/defang-io/CLI-auth-15e8fc22c43080dd82aae73893f1c781?pvs=4
=> Require auth for some CD tasks

src/cmd/cli/command/commands.go
* Decect GCP env for provider picker
Taken out of #930
=> Detect gcp in provider picker

src/pkg/cli/getServices.go, src/pkg/cli/getServices_test.go
I thought the `Name` column was the project name, but it was the service name, so I renamed it to `Service` instead.
=> Change name column header

src/pkg/cli/client/byoc/baseclient.go, src/pkg/clouds/aws/ecs/cfn/setup_test.go, src/pkg/clouds/aws/ecs/run.go, src/pkg/cmd/factory.go, src/pkg/utils.go, src/pkg/utils_test.go
Deploying to AWS BYOC from Windows fails:
```
Error: operation error ECS: RunTask, https response error StatusCode: 400, RequestID: c37676a2-28a6-44b6-a79d-b79502af2b6c, InvalidParameterException: startedBy cannot be blank.
```
=> Use USERNAME on Windows

src/pkg/cli/client/byoc/gcp/byoc.go, src/pkg/clouds/gcp/cloudrun.go, src/pkg/clouds/gcp/iam.go, src/pkg/clouds/gcp/project.go
Enable standalone debugging.
[
](https://github.com/DefangLabs/defang/issues/941)
=> in progress to allow debug and tail commands

src/pkg/cli/subscribe.go, src/pkg/cli/subscribe_test.go
Create unit tests for subscribe.go
#975
=> Create tests for subscribe

src/pkg/cli/client/byoc/gcp/byoc.go
=> Allow pulumi to output color log for gcp

.devcontainer/devcontainer.Dockerfile, .devcontainer/devcontainer.json, Makefile, defang.code-workspace, flake.nix
I'm setting up a new laptop, and I'd like to avoid installing golang locally. I've been using devcontainers for other projects and I thought it would be easy to set up for `defang`. Hopefully it will also make it easier for others to contribute. If you have the [Dev Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension for VSCode, you will be automatically prompted to open the project in a dev container.
=> Setup devcontainer

src/pkg/cli/client/byoc/gcp/byoc.go, src/pkg/cli/client/byoc/gcp/query.go, src/pkg/cli/client/byoc/gcp/stream.go
=> Support log filter for gcp provider

src/pkg/cli/client/byoc/aws/byoc.go
Lot of AWS errors fail as `OperationError` so we need to check the contents to decide whether or not it's a credential error. Since there are many kind of credentials (profile, from env, ec2imds, etc.) we only check for top-level "STS".
Fixes #994
=> Only show AWS cred err on STS errs

src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/clouds/aws/ecs/logs.go
* Escape the filter pattern (because AWS CW supports some regex features)
* Also apply filter to query (not just tail)
Missed from #976
=> Escape AWS CW filter pattern

src/pkg/cli/client/grpc_logger.go
This way we can correlate which the calls from the CLI with the calls on the backend.
=> Set request-Id in gRPC client

src/cmd/cli/command/cd.go, src/cmd/cli/command/compose.go, src/pkg/cli/tail.go, src/pkg/cli/tail_test.go
SetLocaltoUTC() -> SetLocalToUTC()
Typo in function naming
=> Typo on camelCase function name

src/.goreleaser.yml
This reverts commit e1327d9be5cd8d9b628d29a8c32e2f7aea1a06cb.
reverting change. winget failed to deploy.
revert.
=> Revert "enable winget-pkg manifest creation and PR (#1054)"

README.md, pkgs/defang/cli.nix, pkgs/npm/README.md, pkgs/npm/package.json
Update branding for github and npm.
nonr
=> update branding - npm and github

src/pkg/cli/compose/config_detector.go, src/pkg/cli/compose/config_detector_test.go, src/testdata/configdetection/compose.yaml, src/testdata/configdetection/compose.yaml.fixup, src/testdata/configdetection/compose.yaml.golden
…to avoid false positives. I used the exact values from the Compose file in the unit test, to ensure these are now no longer detected as secrets.
=> Bump high-entropy detector threshold

src/pkg/cli/compose/validation.go
`x-defang-llm` is now supported!
=> avoid warning about x-defang-llm

pkgs/npm/package-lock.json
Probably related to upgrading these dependencies in #1090 .
I had to run `cd pkgs/npm && npm install`
=> update npm package lock

src/.goreleaser.yml
Update slogan for winget.
None
=> update winget branding

src/pkg/cli/compose/fixup.go, src/pkg/cli/compose/validation.go
Add warning for users trying to use auto-scaling on playground.
fixes #1667
=> CLI auto-scaling warning

src/pkg/cli/compose/fixup.go, src/pkg/cli/compose/serviceNameReplacer.go, src/pkg/cli/compose/serviceNameReplacer_test.go, src/testdata/fixupenv/compose.yaml, src/testdata/fixupenv/compose.yaml.fixup, src/testdata/fixupenv/compose.yaml.golden, src/testdata/fixupenv/compose.yaml.warnings, src/testdata/networks/compose.yaml, src/testdata/networks/compose.yaml.fixup, src/testdata/networks/compose.yaml.golden, src/testdata/networks/compose.yaml.warnings
Remove special cased "private" and "public" networks, in favor of "default" and `internal` flag.
=> Networking

src/cmd/cli/command/mcp.go
=> Use real version

src/pkg/mcp/README.md, src/pkg/mcp/setup.go, src/pkg/mcp/tools/services.go
Currently right now, I only support normal vscode. This PR should give support to vscode insider as well.
=> Setup case for vscode-insider

src/pkg/mcp/tools/destroy.go
Need to update a description for destroy MCP.
=> Update destroy description

README.md, src/cmd/cli/command/commands.go
Useful to demo our generator with different editors, eg. windsurf.
=> Add DEFANG_EDITOR env var

src/cmd/cli/command/commands.go
=> Change short description

src/cmd/cli/command/cd.go, src/cmd/cli/command/commands.go, src/cmd/cli/command/compose.go, src/cmd/cli/command/mode.go, src/pkg/cli/preview.go, src/pkg/cli/preview_test.go
This is needed for cost estimation for different deployment modes.
Fixes #1022
=> feat: support --mode for cd preview

src/pkg/cli/debug.go
Change wording to avoid devs thinking their files got updated.
=> Update debug.go: better wording

.github/workflows/go.yml, src/Dockerfile, src/Makefile
* fix caching
* use `VERSION` from outside
=> Set Docker image VERSION from outside

pkgs/defang/cli.nix, src/cmd/cli/command/commands.go, src/go.mod, src/go.sum, src/pkg/cli/compose/fixup.go, src/pkg/cli/compose/validation.go, src/testdata/provider/compose.yaml.golden
=> Update compose go

src/pkg/cli/client/byoc/gcp/query.go, src/pkg/cli/compose/validation.go, src/pkg/clouds/gcp/label.go, src/testdata/fixupenv/compose.yaml.warnings, src/testdata/longname/compose.yaml.warnings
GCP does not allow upper case values, so make all upper case letters in label values to lower case.
=> Make service label value safe for gcp

src/pkg/cli/client/byoc/gcp/byoc.go, src/pkg/cli/client/byoc/gcp/stream.go, src/pkg/cli/client/byoc/gcp/stream_test.go, src/pkg/cli/compose/validation.go, src/pkg/clouds/gcp/label.go, src/pkg/clouds/gcp/label_test.go, src/testdata/fixupenv/compose.yaml.warnings, src/testdata/longname/compose.yaml.warnings
So normalized service names can be restored for display and check service status.
=> Do not allow service names differ only by case, gcp restore service names using local map

src/cmd/cli/command/mcp.go, src/pkg/mcp/tools/common.go, src/pkg/mcp/tools/config.go, src/pkg/mcp/tools/deploy.go, src/pkg/mcp/tools/listConfig.go, src/pkg/mcp/tools/removeConfig.go, src/pkg/mcp/tools/setConfig.go, src/pkg/mcp/tools/tools.go
- Added list config to mcp
- Added remove config to mcp
- Renamed config to set config in mcp
- Improved the server instrctuions in mcp
- Set debug mode only to mcp serve
=> Added config MCP tool

src/pkg/cli/client/byoc/do/byoc.go
Check results of err returned from DO function call before trying to use data. if err is not nil then the rest of the function results are questionable.
None
=> fix to nil reference panic, make sure we handle errs before using data

.github/workflows/nightly.yml
nightly build fails to find goreleaser.yml. update to correct working directory
fixes #580
=> fix nightly build not finding config

src/pkg/cli/client/byoc/aws/byoc.go
First deployment would set `UseAcmeCert` to `true`, but then, after DNS records got updated to match any `publicFqdn`, the second deployment would leave `UseAcmeCert` as `false`, causing ACME to be removed.
=> fix(acme): ignore CNAME during 'up'

src/cmd/cli/command/estimate.go
In #1243, while restoring the ability to run estimation previews in your own account, I failed to call `canIUseProvider` which configures the provider cd image.
This PR also removes behaviours which would assume that the user intended to set `-P` if cloud credentials were in their environment. Now `-P` is required even if you have cloud credentials in your environment.
#1243
=> Add provider usage check before invoking estimation preview

src/pkg/mcp/setup.go
If we are running `defang mcp setup`, then we know we already have the defang cli installed, so we can use that directly instead of delegating to `npx`.
=> use executable's abs path when configuring mcp server

pkgs/defang/cli.nix, src/go.mod, src/go.sum, src/pkg/cli/compose/context.go, src/pkg/cli/compose/context_test.go, src/pkg/cli/compose/fixup.go, src/pkg/cli/compose/validation.go, src/testdata/models/compose.yaml, src/testdata/models/compose.yaml.fixup, src/testdata/models/compose.yaml.golden, src/testdata/models/compose.yaml.warnings
Support for https://docs.docker.com/reference/compose-file/models/
=> Support new Docker models

src/pkg/migrate/heroku.go, src/pkg/migrate/migrate_test.go
Adding three new pieces of context for heroku compose generation:
* pg info (which includes postgres version)
* dyno size(so we can specify service resources)
* release tasks (so we can create a release services which run one-time tasks)
=> add additional heroku context for compose generation

src/pkg/login/login.go
Resolving an auth regression introduced in #1354
=> replace global client with new one after cli.Connect

src/pkg/migrate/migrate.go, src/pkg/migrate/migrate_test.go
this was moved to deploy-time in #1392
=> remove obsolete command fixup from compose generation

.github/workflows/go.yml, Makefile, flake.nix, src/cmd/cli/command/commands_test.go, src/cmd/cli/command/configrandom_test.go, src/go.mod, src/pkg/cli/compose/compose_test.go, src/pkg/cli/compose/context_test.go
Copy `flake.lock` from MVP repo and fix linting errors.
=> fix: update Go to 1.24

src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/cli/client/byoc/do/byoc.go, src/pkg/cli/client/byoc/gcp/byoc.go
=> fix: set Mode in ProjectUpdate PB

src/pkg/mcp/prompts/awsBYOC.go
rename AWS_Credential to AWS Credential
=> rename aws argument

src/pkg/mcp/setup.go, src/pkg/mcp/setup_test.go
Fix mcp setup for cursor by targeting .cursor/mcp.json
fixes #1386
=> fix mcp setup for cursor target

pkgs/defang/cli.nix, src/go.mod, src/go.sum, src/pkg/mcp/README.md, src/pkg/mcp/setup.go, src/pkg/mcp/setup_test.go
Makes it possible to install the Defang MCP command in the [OpenAI Codex cli](https://github.com/openai/codex/blob/main/docs/config.md#mcp_servers)
=> Enable OpenAI Codex MCP Support

src/pkg/cli/client/byoc/aws/byoc.go, src/pkg/cli/client/byoc/aws/subscribe.go, src/pkg/cli/client/byoc/aws/subscribe_test.go
Fix race condition which may cause writing to channel to fail. 
fixes #1450
=> fix potential panic on send to closed channel

Makefile, src/cmd/cli/command/mcp.go, src/pkg/mcp/mcp_server.go, src/pkg/mcp/tools/deploy.go, src/pkg/mcp/tools/destroy.go, src/pkg/mcp/tools/estimate.go, src/pkg/mcp/tools/listConfig.go, src/pkg/mcp/tools/login.go, src/pkg/mcp/tools/login_test.go, src/pkg/mcp/tools/removeConfig.go, src/pkg/mcp/tools/services.go, src/pkg/mcp/tools/setConfig.go, src/pkg/mcp/tools/tools.go
Refactoring tool setup to put all of the tool descriptions and parameter schemas in the same file, wrapped up in one function that returns the list of tools so that we can derive the server instructions from that list of tools and their descriptions
=> Refactor tool setup

src/pkg/mcp/tests/client_test.go, src/pkg/mcp/tools/default_tool_cli.go, src/pkg/mcp/tools/deploy.go, src/pkg/mcp/tools/deploy_test.go, src/pkg/mcp/tools/destroy_test.go, src/pkg/mcp/tools/estimate.go, src/pkg/mcp/tools/interfaces.go, src/pkg/mcp/tools/listConfig_test.go, src/pkg/mcp/tools/login.go, src/pkg/mcp/tools/removeConfig_test.go, src/pkg/mcp/tools/services.go, src/pkg/mcp/tools/services_test.go, src/pkg/mcp/tools/tools.go
Remove duplicate code for interfaces used in mcp tools
fixes #1422
=> clean by removing duplicate code.
