README.md

Add shell script installation and use triple backtick for easy copying.

Installation Instruction Changes

---

src/cmd/cli/main.go
src/pkg/aws/common.go
src/pkg/cli/connect.go

This would make sure defang cli would behave exactly the same in how to look up the credentials as the aws cli, since aws cli have a different behavior for sso logged in users, which does not save the credentials to the standard location the go sdk check, and if there is a wrong/expired credential saved with the same profile name, the aws cli would still succeed but defang cli would fail which could be very confusing for customers.
Also updated the hint for if the aws credentials expired. 
Do not defaults to aws provider when there is only AWS_REGION environment variable is detected.

Use AWS cli export credential as the first provider in the chain

---

src/pkg/cli/bootstrap.go
src/pkg/cli/common.go
src/pkg/cli/compose.go
src/pkg/cli/composeStart.go
src/pkg/cli/delete.go
src/pkg/cli/generate.go
src/pkg/cli/restart.go
src/pkg/cli/secretsDelete.go
src/pkg/cli/secretsSet.go
src/pkg/cli/sendMsg.go
src/pkg/cli/tail.go
src/pkg/cli/token.go

Reported by Don: happens because w/ `--dry-run` we don't return an error, but also don't return a project, but we'd still try to print the endpoints. Fixed by returning a specific dry-run error.

cli: fix panic/segfault in dry-run compose

---

src/pkg/aws/ecs/logs.go
src/pkg/aws/ecs/tail.go
src/pkg/aws/ecs/tail_test.go
src/pkg/cli/client/byoc.go

Fixes #129 
Fixed by using the ability of cloudwatch API to tail not just a loggroup but a specific logstream: we know the task ID (we got it from the RunTask API) so we only tail that logstream.

tail: only show logs from my cd

---

src/cmd/cli/main.go
src/pkg/cli/client/grpc.go
src/pkg/cli/client/state.go
src/pkg/cli/login.go

…so we can correlate subsequent invokes, even without login.
* also track help command
* remove track go-routines because process may exit before track completes

cli: persist anonymous ID

---

src/pkg/aws/ecs/cfn/setup.go
src/pkg/aws/ecs/cfn/setup_test.go
src/pkg/aws/ecs/cfn/template.go
src/pkg/aws/ecs/common.go
src/pkg/aws/ecs/common_test.go
src/pkg/cli/client/byoc.go
src/pkg/cmd/run.go
src/pkg/docker/run_test.go
src/pkg/docker/setup.go
src/pkg/local/local.go
src/pkg/local/local_test.go
src/pkg/types/driver.go

Extracted from #131 
* rename `Task` to `Container` (and `tasks` to `containers`)
* fixed ECS unit test
* fixed mem calculation (min 6MiB, not +6)
* set MinDelay=1 during stack delete/teardown
* removed hardcoded workingdir

Crun sidecar support

---

src/cmd/cli/main.go
src/pkg/aws/secrets.go
src/pkg/cli/client/byoc.go
src/pkg/cli/client/client.go
src/pkg/cli/client/grpc.go
src/pkg/cli/colorizer.go
src/pkg/cli/secretsDelete.go
src/pkg/cli/secretsSet.go
src/pkg/types/driver.go
src/protos/io/defang/v1/defangv1connect/fabric.connect.go
src/protos/io/defang/v1/fabric.pb.go
src/protos/io/defang/v1/fabric.proto

- `echo abc | defang secret set -n asdf` was broken (would show prompt, did not detect pipe)
- support `defang secret delete -n foo -n bar`
- fix secret prompt coloring (by using survey lib; note #95 )
- support multi-line secrets

cli: fix secret set prompt

---

src/cmd/cli/main.go
src/pkg/cli/client/byoc.go
src/pkg/cli/client/client.go
src/pkg/cli/client/grpc.go
src/pkg/cli/composeRestart.go
src/pkg/cli/getServices.go
src/pkg/cli/restart.go

Both BYOC and Playground show only names now:
```
$ defang ls
* Connecting to fabric-prod1.defang.dev:443
services:
- service:
name: api-production
- service:
name: hasura-production
- service:
name: heimdall-production
- service:
name: kratos-production
- service:
name: web-production
To see more information about your services, do:
defang ls -l
```

feat: ls parity between BYOC and playground

---

.github/workflows/go.yml
pkgs/defang/cli.nix

and add CI gate to catch mistaken `vendorHash`.
The flake is updated automatically, but we have no automation to update vendorHash (and commit to GIT) so for now adding a CI check. Should check https://goreleaser.com/customization/nix/

nix: update vendorHash

---

src/pkg/cli/client/byoc/byoc.go
src/pkg/cli/client/byoc/clouds/aws.go
src/pkg/cli/client/byoc/clouds/byoc_integration_test.go
src/pkg/cli/client/byoc/clouds/byoc_test.go
src/pkg/cli/client/byoc/clouds/stream.go
src/protos/io/defang/v1/fabric.pb.go
src/protos/io/defang/v1/fabric.proto

This avoids multiple route53 zones called `internal` which are impossible to tell apart.
@kt5356 this PR also moves the BYOC test files into the clouds folder. In fact, those files are specific for the AWS implementation, so should probably be in its own aws package.
Fixes https://github.com/defang-io/defang-mvp/issues/555

fix: use project name for private zone

---

src/cmd/cli/command/commands.go

#97 
Add portal link to command line response on **defang compose up** and **defang compose start**

Show portal url in command line response when deploying to defang cluster

---

src/cmd/cli/command/commands.go
src/cmd/cli/main.go
src/cmd/crun/main.go
src/cmd/gendocs/main.go
src/pkg/cli/agree_tos.go
src/pkg/cli/bootstrap.go
src/pkg/cli/client/byoc/clouds/common.go
src/pkg/cli/common.go
src/pkg/cli/compose.go
src/pkg/cli/composeStart.go
src/pkg/cli/compose_test.go
src/pkg/cli/connect.go
src/pkg/cli/delete.go
src/pkg/cli/generate.go
src/pkg/cli/login.go
src/pkg/cli/logout.go
src/pkg/cli/restart.go
src/pkg/cli/secretsDelete.go
src/pkg/cli/secretsSet.go
src/pkg/cli/sendMsg.go
src/pkg/cli/tail.go
src/pkg/cli/token.go
src/pkg/cli/whoami.go
src/pkg/cmd/color.go
src/pkg/cmd/common.go
src/pkg/cmd/info.go
src/pkg/term/colorizer.go

This way we can use the output functions (`term.Debug` etc.) from all packages without cyclic imports.

move colorize.go to term package

---

src/pkg/cli/client/byoc/clouds/aws.go
src/pkg/cli/client/byoc/clouds/stream.go

- byocServerStream close does not need to cancel the parent context, context cancellation should always be one direction.
- byocServerStream does not have any operations needs to observe context cancellation, so we do not need a sub context.
- Moved `hasErrCh` detection into byocServerStream, which is where it is only being used.
- Extracted out `parseEvent` function so the main select logic of byocServerStream is easier to read.

Slight clean up of the context propagation

---

.github/workflows/npm-publish.yml

Updates so binary build workflow completes before we run the publish workflow. This workflow is not truly dependent on the "Go package" workflow but if that workflow does not succeed then there is no point in publishing a npm package.

only trigger publish if the release build workflow completes successfully first

---

src/cmd/cli/command/commands.go
src/cmd/cli/command/exitcode.go
src/cmd/cli/main.go
src/pkg/local/local.go
src/pkg/local/local_test.go
src/pkg/term/colorizer.go
src/pkg/term/colorizer_other.go
src/pkg/term/colorizer_test.go
src/pkg/term/colorizer_windows.go

From  https://github.com/muesli/termenv/issues/36

enable ANSI on Windows

---

src/cmd/cli/command/commands.go
src/pkg/cli/agree_tos.go
src/pkg/cli/cert.go
src/pkg/cli/tail.go
src/pkg/term/colorizer.go
src/pkg/term/colorizer_test.go

I think the colorizer.go was getting out of hand. Lots of mixed use of `term.Print(term.Nop, …)` vs `fmt.Print(…)`, so I deleted `term.Nop` and we just use the `fmt` ones for regular prints.
Also simplified the `Flog` function, because it always did a `fmt.Sprintln` which always adds a newline, so the addNewLine=true had no effect. This meant that only `Flogf` used the logic to add a newline. Furthermore, the `log` package adds newline for empty lines, so I copied that behavior.

simplify colorizer

---

src/pkg/cli/compose.go
src/pkg/github/auth.go
src/pkg/term/colorizer.go

show compose progress

---

src/pkg/cli/composeStart.go

In effort to align secrets as environment variables we are moving secrets to environment fields (internally).

move secrets to environmentVars

---

samples/golang/AWS S3/README.md
samples/golang/ChatGPT API/README.md
samples/golang/slackbot/README.md
samples/nodejs/AWS S3/README.md
samples/nodejs/ChatGPT API/README.md
samples/other/vllm/README.md
samples/python/AWS S3/README.md
samples/python/ChatGPT API/README.md

Wait on https://github.com/defang-io/defang/pull/328 to be merged first.
Secrets are being renames config.

update sample docs to use defang config rather than defang secrets

---

src/pkg/cli/composeStart_test.go
src/tests/fixupenv/compose.yaml

Add test to ensure values in environment section without a set value are put in the internal Service.Secrets field.

update test to check for sensitive keys in compose.yaml

---

pkgs/npm/package.json
pkgs/npm/src/cli.ts
pkgs/npm/src/installer.ts

npx swallows postInstall errors so users do not see errors and the cli doesn't execute the defang command.
There's no way (I've found) to cause npx to show error on postInstall so will allow postInstall to pass even if it failed to download. Cli will be run after, it will throw an error there which will be visible from npx.
Fixes #339

show errors on cli run but allow install.js to pass. 

---

README.md
src/pkg/cli/client/byoc/aws/byoc.go

This adds a new CLI env var `DEFANG_CD_BUCKET` to override the bucket used by the `defang cd …` commands. This allows us to clean up old stacks.

add DEFANG_CD_BUCKET override

---

src/pkg/cli/bootstrap.go
src/pkg/cli/cert.go
src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/cli/client/client.go
src/pkg/cli/client/grpc.go
src/pkg/cli/composeDown.go
src/pkg/cli/configDelete.go
src/pkg/cli/configList.go
src/pkg/cli/configSet.go
src/pkg/cli/getServices.go
src/pkg/cli/tail.go

Some commands need the project name to be available (for example SSM resource name or bucket names), but don't need the whole project loaded.
Fixes #348

fix for missing project names

---

src/cmd/cli/command/commands.go
src/cmd/cli/command/version.go
src/cmd/cli/command/version_test.go

dev builds should be considered latest version and not trigger the "update" or "outdated" warnings.

fix version check to handle dev builds

---

src/cmd/cli/command/commands.go
src/cmd/cli/command/track.go

our analytics has many "Compose-Up" events without "Terms" and/or "Login" events, causing weird results in our dashboard. This is because we do login/terms interactively when needed and these were not tracked.
New events are called "Implicit Login" and "Implicit Terms" (compare with "Login Invoked" and "Terms Invoked" for the explicit ones)

track implicit login/terms events

---

.github/workflows/go.yml
src/.goreleaser.yml

This relies on `DISCORD_WEBHOOK_ID` and `DISCORD_WEBHOOK_TOKEN` action secrets, which I got from creating a hook in Discord:

announce releases on discord

---

src/pkg/cli/compose.go
src/pkg/cli/composeStart.go
src/pkg/cli/compose_test.go
src/pkg/cli/compose_validation.go
src/pkg/cli/tail_test.go
src/tests/redis/compose.yaml

Fixes #406 
Fixed up all warnings:
```
WARNING service "x": missing compose directive: restart; assuming 'unless-stopped' (add 'restart' to silence) 
WARNING service "x": missing memory reservation; specify deploy.resources.reservations.memory to avoid out-of-memory errors 
WARNING service "y": missing compose directive: restart; assuming 'unless-stopped' (add 'restart' to silence) 
WARNING service "y": missing memory reservation; specify deploy.resources.reservations.memory to avoid out-of-memory errors 
WARNING service "y": managed Redis service should use a redis image 
WARNING service "z": missing compose directive: restart; assuming 'unless-stopped' (add 'restart' to silence) 
WARNING service "z": missing memory reservation; specify deploy.resources.reservations.memory to avoid …
```

issue warning for stateful images

---

src/cmd/cli/command/commands.go

In Compose, project = folder, so we should not use "service1" as the folder name.

use project1 as default folder

---

src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/cli/client/byoc/aws/stream.go
src/pkg/cli/tail.go
src/pkg/clouds/aws/ecs/ecsserviceaction/aws_event.go
src/pkg/clouds/aws/ecs/ecsserviceaction/ecs_service_action.go
src/pkg/clouds/aws/ecs/ecsserviceaction/marshaller.go
src/pkg/clouds/aws/ecs/ecstaskstatechange/attachment_details.go
src/pkg/clouds/aws/ecs/ecstaskstatechange/attachment_details_details.go
src/pkg/clouds/aws/ecs/ecstaskstatechange/attributes_details.go
src/pkg/clouds/aws/ecs/ecstaskstatechange/aws_event.go
src/pkg/clouds/aws/ecs/ecstaskstatechange/container_details.go
src/pkg/clouds/aws/ecs/ecstaskstatechange/ecs_task_state_change.go
src/pkg/clouds/aws/ecs/ecstaskstatechange/environment.go
src/pkg/clouds/aws/ecs/ecstaskstatechange/marshaller.go
src/pkg/clouds/aws/ecs/ecstaskstatechange/network_binding_details.go
src/pkg/clouds/aws/ecs/ecstaskstatechange/network_interface_details.go
src/pkg/clouds/aws/ecs/ecstaskstatechange/overrides.go
src/pkg/clouds/aws/ecs/ecstaskstatechange/overrides_item.go
src/pkg/clouds/aws/ecs/event.go
src/pkg/clouds/aws/ecs/logs.go

- Handles the ECS events that was routed to cloudwatch logs, parse the etag/service, and display relevant info from the whole event structure
- Fix bug of tail querying older events that does not handle pagination

Handle ECS events from cloudwatch logs

---

src/pkg/cli/client/grpc.go
src/pkg/cli/client/retrier.go
src/pkg/cli/client/retrier_test.go

Automatically retry RPC calls that return `Unavailable` (so we can remove server-side retries)

Auto-retry on Unavailable rpc

---

src/cmd/cli/command/servicemonitor.go
src/pkg/cli/subscribe.go

fix exception in subscribe

---

src/pkg/cli/tail_test.go
src/pkg/term/colorizer.go
src/pkg/term/colorizer_test.go

Regression from #457 https://github.com/DefangLabs/defang/pull/457/files#r1651826691
This broke `echo a | defang config set KEY`

Fix for non-interactive mode

---

.github/workflows/go.yml
src/tests/sanity/compose.yaml

Fixes #491 
Currently blocked by https://github.com/DefangLabs/defang-mvp/pull/762

Update Playground test to use "compose up"

---

src/pkg/cli/compose/compose_test.go
src/pkg/cli/compose/loader.go
src/pkg/cli/tail_test.go
src/tests/alttestproj/altcomp.yaml
src/tests/alttestproj/compose.yaml
src/tests/alttestproj/compose.yaml.convert
src/tests/alttestproj/compose.yaml.golden
src/tests/networks/compose.yaml
src/tests/networks/compose.yaml.convert
src/tests/networks/compose.yaml.golden
src/tests/redis/compose.yaml
src/tests/redis/compose.yaml.convert
src/tests/redis/compose.yaml.golden
src/tests/toomany/compose.yaml
src/tests/toomany/compose.yaml.convert
src/tests/toomany/compose.yaml.golden
src/tests/toomany/compose.yaml.warnings
src/tests/toomany/docker-compose.yml
src/tests/toomany/docker-compose.yml.convert
src/tests/toomany/docker-compose.yml.golden
src/tests/toomany/docker-compose.yml.warnings

also adds a new `toomany` test case to test the case when there are more than 1 compose files in a folder

fix regression when compose name is specified

---

src/cmd/cli/command/version.go
src/cmd/cli/command/version_test.go
src/go.mod
src/pkg/http/client.go
src/pkg/http/get.go
src/pkg/http/post.go
src/pkg/http/put.go
src/pkg/http/put_test.go
src/pkg/http/query.go
src/pkg/http/query_test.go

Fixes #503 
I tried to replace @edwardrf 's "cert" `getWithRetries` code to use the same client, but that code retries 404s as well, where this client (by default) only retries TCP errors and HTTP 5xx.

do http retries

---

.github/workflows/check-sample.yml
.github/workflows/go.yml
flake.nix
src/.goreleaser-prebuilt.yml
src/.goreleaser.yml
src/bin/notarize.sh

Fixes #12 
Reqs:
- MacOS: codesign an notarytool
- Windows: ~~signtool~~ using action
- Nix: nix-prefetch-url (required during the release step)

Sign windows executable

---

.github/workflows/go.yml
src/cmd/cli/command/commands.go
src/cmd/cli/command/hint.go

- editor opened the wrong folder
- hint shows multiple configs on one command (which fails)

fix regressions in generate

---

.github/workflows/go.yml
src/.goreleaser.yml

- fix for Windows: released zip has unsigned exe because we signed after archiving
- fix for MacOS: move notarization into GoReleaser so we don't announce a new version until after notarization succeeded

move notarization into goreleaser

---

src/pkg/cli/compose/convert.go
src/pkg/cli/compose/loader_test.go
src/pkg/cli/compose/validation_test.go
src/tests/alttestproj/compose.yaml.warnings
src/tests/emptyenv/compose.yaml.warnings
src/tests/fixupenv/compose.yaml
src/tests/fixupenv/compose.yaml.convert
src/tests/fixupenv/compose.yaml.golden
src/tests/fixupenv/compose.yaml.warnings
src/tests/redis/compose.yaml.warnings
src/tests/secretname/compose.yaml.warnings
src/tests/testproj/compose.yaml.warnings

The following questions has been repeatedly pop up when a service name replacement is needed, which prevents a successful deployment:
1. The service name need to be replaced has a port not in "host" mode, meaning it has either port->mode:ingress, or missing port config, we do not warn them if this service name is used in other service that depends on it in any of its environment variables.
2. An environment variable could be replaced by a config, though we do have an warning, but it is not clear that we do not do service name replacement in the configured values

Add more warning for service name replacement

---

src/cmd/cli/command/commands.go
src/cmd/cli/command/hint.go
src/pkg/cli/getServices.go

Avoid printing the `-l` hint when there are no services. Instead, show a `defang new` hint.

fix ls hint when no services are found

---

src/cmd/cli/command/commands.go
src/cmd/cli/command/servicemonitor.go
src/pkg/cli/subscribe.go

Refactor the async code. Please compare with #518, I think this one's cleaner.
We should introduce a build failure state to also trigger SERVICE_FAILED so we'll get AI-debugger for build failures. This requires some code in Fabric (probably needs to handle kaniko STOPPED state)

fix compose up wait for state

---

src/cmd/cli/command/commands.go

For now, use a new context for the debug rpc.

quick fix for compose debugging

---

src/cmd/cli/command/commands.go
src/pkg/cli/whoami.go
src/pkg/cli/whoami_test.go

Fixes https://github.com/DefangLabs/defang/issues/566
Depends on https://github.com/DefangLabs/defang-mvp/pull/854
We decided to continue to print the region in the whoami string, but the re-format the values such that the account and region are listed before the tenant. Further, in https://github.com/DefangLabs/defang-mvp/pull/854, we update the playground account name from `defang` to `playground` to further clarify that the user is not using their own cloud.

Reformat whoami string

---

src/cmd/cli/command/commands.go

This flag is not currently useful for end-users, but we do use it internally, so we're going to hide it from the help text for now.

Hide --cluster flag from help text

---

src/cmd/cli/command/commands.go
src/pkg/cli/compose/context.go
src/pkg/cli/compose/context_test.go
src/pkg/cli/debug.go
src/pkg/cli/debug_test.go
src/tests/debugproj/app/Dockerfile
src/tests/debugproj/app/main.js
src/tests/debugproj/compose.yaml
src/tests/debugproj/compose.yaml.convert
src/tests/debugproj/compose.yaml.golden
src/tests/debugproj/compose.yaml.warnings
src/tests/debugproj/main.py

Improvements to #575 
This PR uses the project information to narrow down which files are sent to the debugger. It uses the same "walk dir" that's used by the tarball logic, so it takes `.dockerignore` into account.

Pick right service folder for debugging

---

src/cmd/cli/command/commands.go
src/cmd/cli/command/commands_test.go
src/pkg/cli/compose/compose_test.go
src/pkg/cli/compose/convert_test.go
src/pkg/cli/compose/loader.go
src/pkg/cli/compose/loader_test.go
src/pkg/cli/compose/validation_test.go
src/pkg/cli/composeUp_test.go
src/pkg/cli/debug_test.go
src/pkg/cli/tail_test.go
src/pkg/types/error.go
src/tests/multiple/compose1.yaml
src/tests/multiple/compose2.yaml

Fixes #509 
In #500, we were concerned that the presence of both a `compose.yaml` and ` docker-compose.yaml` file could be confusing, so we decided to return an error and exit early. However, `compose-go` _does_ log out a warning in this scenario, as does `docker compose`. We've changed our mind and decided to aim for closer parity with docker here by reverting to logging the warning and continuing with `compose.yaml`.
While implementing this, in an effort to bring us to closer parity with docker compose, we decided to go ahead and add support for passing `-f` multiple times—adding support for multiple compose files.

Support for multiple compose files

---

src/cmd/cli/command/commands.go
src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/cli/client/byoc/aws/byoc_test.go
src/pkg/cli/client/byoc/baseclient.go
src/pkg/cli/client/byoc/do/byoc.go
src/pkg/cli/client/client.go
src/pkg/cli/client/playground.go
src/pkg/cli/compose/compose_test.go
src/pkg/cli/compose/convert_test.go
src/pkg/cli/compose/loader.go
src/pkg/cli/compose/loader_test.go
src/pkg/cli/compose/validation_test.go
src/pkg/cli/composeUp_test.go
src/pkg/cli/debug_test.go
src/pkg/cli/tail_test.go

This pull request aims to add support for running `defang compose` commands outside of the project's working directory by using the `--project-name` CLI flag. In order to accomplish this, the `compose.Loader` has been refactored to accept a `projectName` and to avoid trying to read the `compose.yaml` file from disk unless absolutely necessary.
Many commands do not require any project information aside from the name, so will not need to read the compose file if the project name is passed using this new flag.
The `compose.Loader` will keep a reference to the project name passed by `--project-name` flag, or by the `COMPOSE_PROJECT_NAME` env var. If a project name has not been passed through the cli flag or environment, the `compose.Loader` will read the `compose.yaml` file from the path …

Add --project-name cli flag. Lazily load project name from flags, env, or compose file

---

src/cmd/cli/command/commands.go

Fixes https://github.com/DefangLabs/defang/issues/612
@lionello intended to define aliases for these commands in https://github.com/DefangLabs/defang/commit/1701383f6f876eb20273c9b856e02bf7df47c26a
We will have to find another way.
`Command.AddCommand` sets the command's `parent`—meaning that it will in-effect _move_ the command from any previous parent to a new one.
See [spf13/cobra/command.go#L1312
](https://github.com/spf13/cobra/blob/756ba6dad61458cbbf7abecfc502d230574c57d2/command.go#L1312)

Avoid adding subcommands to multiple parent commands

---

src/cmd/cli/main.go

Results in a segment.com event like this:
```
{
"context": {
"library": {
"name": "analytics-go",
"version": "3.0.0"
},
"os": {
"name": "darwin",
"version": "arm64"
}
},
"event": "Panic",
"integrations": {},
"originalTimestamp": "2024-08-08T22:36:33.233736594Z",
"properties": {
"error": "runtime error: index out of range [1] with length 0",
"stack": "goroutine 1 [running]:\nruntime/debug.Stack()\n\t/nix/store/v8llgr5prc0rawmgynacggg0q4pbvk5w-go-1.21.10/share/go/src/runtime/debug/stack.go:24 +0x64\nmain.main.func1()\n\t/Users/…/dev/defang/src/cmd/cli/main.go:16 +0x40\npanic({0x10464afe0?, 0x14000154870?})\n\t/nix/store/v8llgr5prc0rawmgynacggg0q4pbvk5w-go-1.21.10/share/go/src/runtime/panic.go:914 +0x218\ngithub.com/DefangLabs/defang/src/pkg/cli/client/byoc/aws.(*ByocAws).BootstrapList(0x1400 …
```

Track CLI panics

---

src/pkg/cli/compose/validation.go

Edited the warning message to specify that provider specific defaults are being used.

Fix: Reservations warning should mention defaults (Issue #447)

---

src/cmd/cli/command/commands.go
src/pkg/cli/agree_tos.go
src/pkg/cli/client/state.go
src/pkg/cli/client/state_test.go

Fixes https://github.com/DefangLabs/defang-mvp/issues/711
We avoid login during the first `defang generate` to lower the barrier of entry, but we still need to ask for terms agreement. Later, when the user logs in they'll get asked again, because the agreement was never persisted on the server.
This PR will track the agreement in the user's state file. To avoid changes in terms between the first (offline) agreement and a future log in, we track the time and ask again if more than 1 day has passed.

Persist offline terms agreement

---

.github/workflows/install.yml
src/bin/install

Our installer should use `GH_TOKEN` or `GITHUB_TOKEN`, if available, when using the GitHub API, to avoid hitting the anonymous user rate limits. In case the token is available, but invalid, it falls back to anonymous access.
This avoids failures in the CI when the limits are hit:
https://github.com/DefangLabs/defang-mvp/actions/runs/10549441099/job/29224573549#step:6:24
See https://everything.curl.dev/cmdline/exitcode.html error code 22.

Use GH token in installer

---

src/pkg/cli/client/playground.go
src/pkg/cli/destroy_test.go

Bugfix: Use the local project name with `defang compose down`.
Background:
It looks like we added the `Project` field to the `DeleteRequest` in #560 but instead of sourcing the project name from the local compose file, we used the value returned by `GetServices`, which is unfortunately still populated with the tenant name. Instead, we should source the project name from the local compose file or from the `--project-name` CLI flag.

Bugfix: Pass local project name to Destroy

---

src/pkg/cli/compose/convert.go
src/pkg/cli/compose/convert_test.go
src/pkg/cli/compose/validation.go
src/pkg/cli/tail.go
src/tests/ports/compose.yaml
src/tests/ports/compose.yaml.convert
src/tests/ports/compose.yaml.golden
src/tests/ports/compose.yaml.warnings
src/tests/testproj/compose.yaml.warnings

- Fix regression in `tail` https://github.com/DefangLabs/defang/pull/613/files#diff-eaaea9856777a2f5870fca35a2c52aef840f045c6558b3b56def7132d9125e95L364
- In https://github.com/DefangLabs/defang-mvp/pull/939 we added "published" ports to all generated files (because of #546) but this shows a warning; made the warning into debug-only message
- Added port numbers to warnings to help identify the offending port
```
! Published ports are ignored in ingress mode
```

Fix Compose port warnings

---

src/pkg/cli/client/byoc/baseclient.go

Since #599, we already consider the `COMPOSE_PROJECT_NAME` env var when loading the project name, so this fallback is redundant. We also want to suggest using the `--project-name` flag instead of the env var.

Remove obsolete project name fallback

---

src/pkg/cli/client/byoc/aws/byoc.go

Subscribe would not work for cd remote commands as the task is running in the cloudformation cd cluster instead of the service cluster, which the ecs events will not be routed to cloudwatch logs where subscribe is following.

Wait for task finish if we are following a single task

---

src/cmd/cli/command/commands.go

The `cd` subcommands are not very useful to end-users right now, but they are unfortunately listed first in the documentation nav bar when naturally sorted alphabetically. This PR "hides" the `cd` subcommands from the docs and from the cli helptext, but the commands are still usable to us. We can revisit documenting them publically when we have a clearer user-story for them.

hide cd subcommands from the docs

---

src/cmd/cli/command/compose.go

Currently, when CI has no tail permission, tail would fail, and the permission err gets returned when context is cancelled.

Do not return err if we failed to tail

---

src/cmd/cli/command/commands.go
src/pkg/cli/client/provider.go
src/pkg/cli/connect.go

Fixes #667 by no longer using AWS provider when AWS env vars were found. You now need to explicitly mention `--provider=aws`
Technically this is a breaking change, so perhaps it's time to bump the next release to 0.6.0

Make AWS provider explicit

---

src/pkg/cli/cert.go
src/pkg/cli/cert_test.go

- Cache root resolver dns result for http client for 1m
- also add more delay between triggering tries.
- Fails cert gen command and prompt for retry when trigger fails
Reproduced issue and verified fixed:
```
* defang.lol DNS is properly configured!
* Triggering cert generation for defang.lol
- Redirecting from http://defang.lol to http://fabric-prod1.defang.dev:80/?shard=45b05cc9&
- Error fetching http://defang.lol: HTTP 503: failed to update acme certificate: failed to get certificates: obtaining certificate: solving challenge: defang.lol: [defang.lol] authorization failed: HTTP 400 urn:ietf:params:acme:error:dns - DNS problem: NXDOMAIN looking up A for defang.lol - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for defang.lol - check that a DNS …
```

Cache root resolver dns result for http client for 1m

---

src/pkg/quota/service.go
src/pkg/quota/service_test.go

Fixed https://github.com/DefangLabs/defang/issues/668
The solution to this error is too complex to describe inline. Add a link to a docs page with more information.
**Todo**:

add link to invalid healthcheck error

---

src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/clouds/aws/ecs/logs.go
src/pkg/clouds/aws/ecs/run.go

Reverts DefangLabs/defang#690
This caused a panic:
```
panic: taskArn is nil
goroutine 183 [running]:
github.com/DefangLabs/defang/src/pkg/clouds/aws/ecs.WaitForTask({0x101cc6e60?, 0x140003aae60?}, 0x0?, 0xb2d05e00?)
/Users/llunesu/dev/defang/src/pkg/clouds/aws/ecs/logs.go:439 +0x148
github.com/DefangLabs/defang/src/pkg/cli/client/byoc/aws.(*ByocAws).Follow.func1()
/Users/llunesu/dev/defang/src/pkg/cli/client/byoc/aws/byoc.go:501 +0x40
created by github.com/DefangLabs/defang/src/pkg/cli/client/byoc/aws.(*ByocAws).Follow in goroutine 1
/Users/llunesu/dev/defang/src/pkg/cli/client/byoc/aws/byoc.go:500 +0x774
```
The right fix is to have BYOC `Subscribe` check the CD task status (or ECS events) in addition to the services.

Revert "Stop the cli when CD task fails during deployment"

---

src/cmd/cli/command/commands.go
src/cmd/cli/command/compose.go
src/pkg/cli/compose/compose_test.go
src/pkg/clouds/aws/ecs/logs.go

The AI debugger got some false-negatives, because users get prompted to use the debugger when they "cancel" the tail that follows a `compose up`, even though there are no reasons to debug.

Don't show debugger on Ctrl-C

---

src/pkg/cli/connect.go

Similar to what we print with AWS
```
$ defang compose up
* Using Defang Playground; consider using BYOC (https://s.defang.io/byoc)
```

Show a message about playground

---

src/pkg/cli/compose/context.go

I saw this warning while deploying the rails sample today, which is just under 100 files in the docker build context (after applying the ignore rules). It's a pretty small stock rails app, so lots of files, but also completely reasonable.
I think this warning adds more friction than value at this low limit. I propose we increase it to 100, which will get us out of the way for many legitimate use-cases while still catching problematic scenarios.

Increase build context warning limit to 100

---

src/cmd/cli/command/compose.go

…because all our samples now say `docker compose up --build`, see https://github.com/DefangLabs/samples/pull/222, so would want that to work with `defang` too.

Add hidden --build flag for docker compat

---

src/pkg/clouds/aws/ecs/cfn/template.go

Regression from #594 (probably me)
```
Resource handler returned message: "Invalid request provided: Create TaskDefinition: workingDirectory should be at least 1 characters long. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: fed3bca4-6f8c-44e5-bcd0-752d40d941b6; Proxy: null)" (RequestToken: 918aaba1-1fa7-79cb-2133-49178aa8263d, HandlerErrorCode: InvalidRequest)
```

Fix for AWS BYOC empty WorkingDirectory

---

src/pkg/cli/tail.go
src/pkg/clouds/aws/ecs/event.go

Make all ecs events update with host="ecs", except the kaniko task being host="kaniko" which will be hidden during normal log level

Hide ecs events logs in non-verbose mode

---

src/cmd/cli/command/compose.go

This fixes the red-herring `Error: missing tail permission` in GitHub Action output when the deployment fails because of a build/deployment error.
The CI does not have permission to `tail` so it'll wait for the deployment to succeed or fail, but if the deployment does fail, it ends up printing the "missing tail permission" error and not the error that caused the failure.
From https://discord.com/channels/1233224785450897561/1236397762929627157/1295947226283245601

Print real error, not missing tail perm

---

src/cmd/cli/command/commands.go
src/pkg/cli/compose/loader.go

workingDir was removed in #756  as it was interfering with current working directory flag. Cleaning up missed code.

remove extraneous workingDir from Loader struct.

---

src/cmd/cli/command/commands.go

This fixes the printed hint when a user news a sample with a config used by many services:
```
* Code generated successfully in folder bullmq-bullboard-redis
Check the files in your favorite editor.
To deploy the service, do `cd bullmq-bullboard-redis` and 
defang config create QUEUE
defang config create BOARD_PASSWORD
defang config create QUEUE
defang config create QUEUE
For help with warnings, check our FAQ at https://docs.defang.io/docs/faq
```

Avoid duplicate defang config hints

---

src/cmd/cli/main.go

These are not Cobra commands so version property was not added. 
```json
{
"event": "User Interrupted",
"properties": {
"$source": "segment",
"event_original_name": "User Interrupted",
"id": "eb5a9180-658d-56cb-9dc6-b6d356b503f4",
"segment_source_name": ""
}
}
```

Add CLI version to panic/interrupt

---

src/pkg/cli/cert.go

Update text for when there are no domains in the compose files. Make it clear where the issue is.

update cert info when no domains found in compose file.

---

src/cmd/cli/command/commands.go

Users might have both AWS and DO creds in env so we should show both warnings "Did you mean --provider=aws" as well as "Did you mean --provider=digitalocean"

Detect the creds of all providers, not just 1

---

src/cmd/cli/command/commands.go
src/cmd/cli/command/compose.go
src/pkg/cli/cert_test.go
src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/cli/client/byoc/do/byoc.go
src/pkg/cli/client/client.go
src/pkg/cli/client/playground.go
src/pkg/cli/compose/context.go
src/pkg/cli/compose/convert.go
src/pkg/cli/compose/convert_test.go
src/pkg/cli/compose/validation_test.go
src/pkg/cli/composeUp.go
src/pkg/cli/composeUp_test.go
src/pkg/cli/getServices.go

Fixes #123 by adding a new `defang cd preview` command. Technically, this command should live under `defang compose` because it needs the Compose file, but it's BYOC only and shows raw Pulumi output, so for pros only.
If we're happy with this, we can "mirror" `preview` to top-level, like `defang preview` cf. `defang up` etc.

Add preview mode

---

README.md
src/pkg/cli/client/byoc/aws/byoc.go

We were using `latest` on AWS (not on DO) and this can cause issues when Pulumi changes the schemas.

add DEFANG_PULUMI_VERSION env

---

src/pkg/clouds/aws/ecs/cfn/setup.go
src/pkg/clouds/aws/ecs/cfn/waiter.go

because when a new TaskDef (eg. when an image tag is changed) is created, the ARN in the driver was not updated.
This fixes the following error:
```
Error: operation error ECS: RunTask, https response error StatusCode: 400, RequestID: eda80292-edce-428d-b040-410665f3c619, InvalidParameterException: TaskDefinition is inactive
```

Fix TaskDefinition inactive error

---

src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/clouds/aws/route53.go

We need to stick to the old way (no delegation set) for existing BYOC project, because deployment would fail when CD tries to create an already existing private hosted zone.
Fixes regression from #770

Fix for old BYOC projects

---

src/pkg/cli/compose/convert.go
src/pkg/cli/compose/serviceNameReplacer.go
src/pkg/cli/compose/serviceNameReplacer_test.go
src/tests/fixupenv/Dockerfile
src/tests/fixupenv/compose.yaml
src/tests/fixupenv/compose.yaml.convert
src/tests/fixupenv/compose.yaml.golden
src/tests/fixupenv/compose.yaml.warnings

fixes #394 
Extract out service name replacement into it's own struct and function
Use same service name replacement for build arguments

dns fixup in build args

---

src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/cli/client/byoc/do/byoc.go
src/pkg/logs/log_type.go
src/pkg/logs/log_type_test.go

Depends on https://github.com/DefangLabs/defang/pull/769 and https://github.com/DefangLabs/defang-mvp/pull/1016
This PR implements build log partitioning for AWS and DO BYOC clients.

Partition Build Logs from Service Logs

---

.github/workflows/go.yml

Common mistake of mine: `${{ predicate && '' || '-test' }}` always evaluates to `-test` regardless of predicate.

fix windows signing cert

---

src/pkg/quota/service.go
src/pkg/quota/service_test.go

Previously with our own protobuf we'd change the protocol to `HTTP`, but that is not a valid value for the compose `protocol` field, so the "tcp" + "ingress" is a valid combination. 
Eventually we should use the new `app_protocol` field (was added to Compose recently) and set it in fixup phase, then we can revive this check.

fix: tcp+ingress is ok

---

src/cmd/cli/command/commands.go

`defang cd preview` would fail when the user is not already logged into Fabric, because the gRPC call to Fabric for the delegated domain would fail silently and return an empty `DOMAIN` string, which would cause an exception within CD.

cd preview needs login

---

src/cmd/cli/command/compose.go
src/pkg/cli/compose/context.go
src/pkg/cli/composeUp.go

Regression from #520
This "broke" the Defang GitHub action CI test.

Fix --dry-run flag

---

src/pkg/cli/upgrade.go

Fixes #658
If you don't have `brew`, it would check whether the executable has the brew prefix `""` which is always true.

Fix for defang upgrade

---

src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/clouds/aws/ecs/cfn/setup.go
src/pkg/clouds/aws/s3.go
src/pkg/clouds/aws/secrets.go
src/pkg/clouds/aws/secrets_test.go

It would look for the bucket name in a CloudFormation stack and fail if it wasn't there.

Fix 1st time BYOC on AWS

---

README.md
src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/cli/client/byoc/aws/byoc_integration_test.go
src/pkg/cli/client/byoc/baseclient.go
src/pkg/cli/client/byoc/do/byoc.go

Adding an env var `DEFANG_PULUMI_DIR` for faster testing of Pulumi CD code. You'd set this var to the folder with the Pulumi code, ie. `…/pulumi` and then when `--debug` it would run Pulumi locally, as opposed to running it in the cloud.

Add DEFANG_PULUMI_DIR env for local Pulumi runs

---

src/pkg/cli/compose/validation.go
src/tests/alttestproj/altcomp.yaml
src/tests/alttestproj/compose.yaml
src/tests/alttestproj/compose.yaml.fixup
src/tests/alttestproj/compose.yaml.golden

That message is not very actionable, so hide it. 
```
! service "service1": no reservations specified; using limits as reservations
```

Hide useless "limits" warning

---

src/pkg/cli/compose/validation.go
src/pkg/cli/tail.go
src/tests/alttestproj/altcomp.yaml
src/tests/alttestproj/compose.yaml
src/tests/alttestproj/compose.yaml.fixup
src/tests/alttestproj/compose.yaml.golden

On BYOC, we only get milliseconds anyway, so let's just stick to milliseconds. On Playground, we do store microseconds in Loki, but we don't really care to show that.

Show timestamps with milliseconds precision

---

src/pkg/cli/compose/validation.go
src/pkg/cli/compose/validation_test.go
src/tests/interpolate/compose.yaml.warnings

This fixes the issue @acote88 ran into when you use a var in an interpolated env. We don't check whether the var is actually added to config, so then this causes an exception during deployment (and on top of that CD keeps running forever.)
Alternatively, we could silently resolve these missing vars to empty string, which is what the shell/docker do, but I think an error avoid wasting time on wondering why something doesn't work.
Fixes https://github.com/DefangLabs/defang-mvp/issues/1148

Check for missing interpolation vars

---

src/cmd/cli/command/compose.go
src/cmd/cli/command/compose_test.go
src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/cli/subscribe.go
src/pkg/clouds/aws/ecs/tail.go
src/pkg/clouds/aws/ecs/tail_test.go

fixes #659 
When doing ```defang compose up``` the CLI will not exit until all services are complete. Because we do not get managed resources (ElastiCache redis/RDS postgres) statuses we will assume they are already up and it'll be up to the service apps to complete before exiting the CLI.

Do not wait on managed resource status to complete.

---

README.md
src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/cli/client/byoc/aws/byoc_test.go
src/pkg/cli/client/byoc/baseclient.go
src/pkg/clouds/aws/ecs/cfn/template.go

We should discuss if we want to enable pull-through caching by default (it saves $$ and is "faster"), especially considering that the pull-through cache repos do not have image lifecycle rules, ie. images never get purged. This is something we'll have to add to the CloudFormation template eventually. See https://github.com/aws/containers-roadmap/issues/1758

Add DEFANG_NO_CACHE env var

---

src/pkg/cli/client/byoc/do/byoc.go

To match the AWS behavior, if no bucket is found we return a `nil` `ProjectUpdate` pointer.

Return nil ProjectUpdate on no bucket

---

src/cmd/cli/command/compose_test.go
src/pkg/cli/client/byoc/do/byoc.go

It looks like https://github.com/DefangLabs/defang/pull/746 introduced a regression where we try to read from an s3 bucket before we've created it. I noticed this trying to deploy a project to a fresh DO account this morning.
This PR permits the returned `"no bucket found"` error and continues with setup in this case.

Avoid "no bucket found" error on first DO deploy

---

src/pkg/cli/cert.go
src/pkg/cli/cert_test.go

Also create fast path for DNS check success, so no need to display the DNS setup instructions.
```
* Checking DNS setup for api21.defang.study
* Please set up a CNAME record for api21.defang.study
api21.defang.study  CNAME or as an alias to [ api.dayifunet.edwardrf.defang.app or api--80.dayifunet.edwardrf.defang.app ]
* Waiting for CNAME record setup and DNS propagation...
* api21.defang.study DNS is properly configured!
* Triggering cert generation for api21.defang.study
* Waiting for TLS cert to be online for api21.defang.study, this could take a few minutes
* TLS cert for api21.defang.study is ready
* Checking DNS setup for web21.defang.study
* web21.defang.study DNS is properly configured!
* Triggering cert generation for web21.defang.study
* Waiting for TLS cert to be online for …
```

Consider redirection a success response for cert gen trigger

---

src/pkg/cli/client/byoc/do/stream.go

When deploying to DO, we open a websocket connection to AppPlatform to tail logs to the user's shell. It seems like the websocket connection is hitting an idle timeout and closing, but our client doesn't expect it, so successful deploys to DO will tail the logs, then timeout and return a non-zero exit code.
I see two potential strategies here:
1. try to reopen the connect
2. anticipate that it will close after some time, and exit 0
This PR implements strategy (2). This means that successful deploys will tail the run logs for a period of time and then the websocket connection will eventually timeout and the process will exit successfully.
This also means that `defang tail` will not behave the same way, which may be surprising to users who expect it to block indefinitely. I think exiting …

Gracefully handle abnormal EOF from DO log stream

---

src/cmd/cli/command/compose.go
src/pkg/cli/getServices.go
src/pkg/cli/getServices_test.go

Currently, you don't notice when there's a compose file in a parent folder:
```
* Using AWS provider
! No services found
```
By showing the project name it is obvious which project is being listed:
```
* Using AWS provider
! no services found in project "dev"
```
(lower case because we print the Go err as-is)

Show project name in ls warning

---

Makefile
src/Makefile

`go test … | sed …` is used to color the failures red, but it would erase the exit code from `go test`. Using `set -o pipefail` to make the pipe fail if the LHS fails.

Use pipefail to fix exit code

---

src/cmd/cli/command/compose.go

Using `.Changed` we can know whether the user overrode the default using `--verbose`

Allow --verbose=0 or false

---

src/pkg/logs/fluent.go
src/pkg/logs/log_type.go
src/pkg/logs/log_type_test.go

Pre-requisite for logtype partitioning in https://github.com/DefangLabs/defang-mvp/pull/1205
* Setting up `LogType` as a bitfield which will be extracted from the `uint32` protobuf attribute `TailRequest.log_type`.
* Add `Service` attribute to `FirelensMessage`

LogType bitfield

---

src/cmd/cli/command/collectUnsetEnvVars_test.go
src/cmd/cli/command/commands.go
src/pkg/cli/client/playground.go

After `defang new` we show the user which configs must be added, but this was missing interpolated vars.

Collect interpolated vars

---

src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/clouds/aws/ecs/common.go

In AWS, `defang tail --etag …` would panic because it can't determine the AWS account ID from the TaskDefARN.

Call FillOutputs in AWS Follow

---

src/cmd/cli/command/commands.go

`Using AWS provider from defang server` is misleading and confusing. Choose a better description for the source:
```
* Using AWS provider from stored preference
```
Feel free to propose better alternatives.

Use a alternative description for stored provider preferrence

---

.github/workflows/install.yml
README.md
src/bin/install
src/pkg/cli/upgrade.go

Replaced the Shell installation `. <(curl -Ls https://s.defang.io/install)` with `eval "$(curl -Ls https://s.defang.io/install)"` to fix the issue of process substitution not being available on older versions of Bash.
There was discussion on other alternatives:
- `. /dev/stdin <<<"$(curl -Ls https://s.defang.io/install)"` - good but a little long-looking
-  ~~`curl -Ls https://s.defang.io/install | sh` - cannot use defang immediately without refreshing after 1st install~~
If you have any opinion on which command to use, please comment below.
Fixes #631 
Updated /defang-docs repo https://github.com/DefangLabs/defang-docs/pull/115
Updated /samples repo https://github.com/DefangLabs/samples/pull/258
Updated /docs-chatbot repo https://github.com/DefangLabs/docs-chatbot/pull/19

Fix installation to work with bash and all versions of shell

---

src/cmd/cli/command/compose.go
src/cmd/cli/command/compose_test.go

Fixing a bug I introduced in #769 which caused the `--type` flag to be redeclared. Added a test to execute the logs command to verify the fix.

avoid redeclaring --type flag on logs cmd

---

.github/workflows/install.yml
README.md
src/bin/install
src/pkg/cli/upgrade.go

`eval "$(curl -fsSL https://s.defang.io/install)"`
Added the `f` and `S` flags to the curl command in the install instructions. The `f` makes sure we don’t eval error messages, and the `S` ensures error messages are shown (even though we add `s` for “silent”).
Linked to #866
Updated /defang-docs repo https://github.com/DefangLabs/defang-docs/pull/115
Updated /samples repo https://github.com/DefangLabs/samples/pull/258
Updated /docs-chatbot repo https://github.com/DefangLabs/docs-chatbot/pull/19

Added f and S flags to curl 

---

.github/workflows/install.yml
README.md
src/bin/install
src/pkg/cli/upgrade.go

`eval "$(curl -fsSL s.defang.io/install)"`.
Removed the `http://` part in curl command from #876.
Improves #876, #866
Updated /defang-docs repo https://github.com/DefangLabs/defang-docs/pull/115
Updated /samples repo https://github.com/DefangLabs/samples/pull/258
Updated /docs-chatbot repo https://github.com/DefangLabs/docs-chatbot/pull/19

Removed http from url in curl command

---

src/bin/install

Added capital `-S` flag to `curl -sfL` script in the `install` file, 
Reordered it to be `curl -fsSL` to be consistent with #876.
Linked to #876

Added -S flag to curl -sfL script

---

src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/cli/client/byoc/aws/byoc_integration_test.go
src/pkg/cli/client/provider.go
src/pkg/cli/composeUp.go

`defang cd preview` is useful in BYOC to see what the diff is, but currently it fails because when there's no delegation ID, the CD TS code assumes a domain was created by the CLI, which is no longer the case, so the call to `getZone` fails. To add insult to injury, the error message does not show what domain is missing, but adding `DEFANG_DEBUG=1` will show the log from https://github.com/DefangLabs/defang-mvp/blob/c532d2431c1b887f5d557cace6624453908530a4/pulumi/shared/aws.ts#L151

Need domain delegation for preview mode

---

src/pkg/cli/debug_test.go
src/pkg/clouds/do/appPlatform/setup.go
src/pkg/clouds/do/appPlatform/setup_test.go

Fix for `only one of jobs.image.tag or jobs.image.digest can be specified` error in DO.

Make image Digest override Tag

---

Makefile
src/Makefile
src/pkg/cli/debug_test.go

Running `golangci-lint run --fix` leaves dirty changes in the working directory if fixes are made. To avoid this, at the cost of more friction, run `golangci-lint run` without `--fix` on pre-commit. Then warn the user to run it again with `--fix` if it fails.

Avoid running lint --fix on pre-commit

---

src/pkg/cli/bootstrap.go

When running `defang cd ls`, prints a message if there are no projects in CD cluster: `No projects found` along with the account ID and region. 
Fixes part of #846

fix "cd ls" output for zero projects

---

src/pkg/cli/compose/validation.go
src/tests/testproj/compose.yaml.warnings

Warn users when there is "Volume" section in compose file. We do not support it.
None

minor fix to warn about volumes definition in compose file

---

src/cmd/cli/command/commands.go
src/cmd/cli/command/commands_test.go
src/cmd/cli/command/compose.go
src/cmd/cli/command/compose_test.go
src/pkg/cli/compose/GPUcounter.go
src/pkg/cli/whoami_test.go

Because of the two clients `client` and `localClient`, the CLI would crap out with an auth error even after interactive login. This is because only one of the client vars got updated.
Fixing this also uncovered a testing error in the gating tests.
Regression from #882

Fix auth error after interactive login

---

src/pkg/cli/common.go
src/pkg/cli/configList.go
src/pkg/cli/configList_test.go
src/pkg/cli/deploymentsList.go
src/pkg/cli/getServices.go
src/pkg/cli/getServices_test.go
src/pkg/term/test_utils.go

There are a few defang commands which print table responses: `defang (deployments|config ls|services)`. This PR updates them to print an "empty message" when there is no data to print instead of printing an empty table.
For example:
```diff
defang services
+no services found in project "foo"
-Name  Etag          PublicFqdn                           PrivateFqdn  Status
```

Print empty state messages instead of empty lists

---

src/pkg/cli/composeUp.go

Avoid exiting if `PutDeployment` fails, because the deployment is already in flight.

Avoid exiting if PutDeployment fails

---

src/pkg/cli/bootstrap.go

Hides `/beta` that appears at the end (or middle, if there is something pending) of a service in `cd ls`
#846

hide /beta in cd ls output

---

src/cmd/cli/command/commands.go
src/cmd/cli/command/commands_test.go
src/cmd/cli/command/deploymentinfo_test.go
src/pkg/cli/compose/compose_test.go
src/pkg/cli/compose/validation_test.go
src/pkg/cli/tail_test.go
src/pkg/logs/logrus_test.go
src/pkg/term/colorizer.go
src/pkg/term/colorizer_test.go
src/pkg/term/table.go
src/pkg/term/test_utils.go

In previous bug fix, a new bug was introduced, the API call to load saved provider was supplied with an empty string as project name and results loading a wrong value, and use have to repeatedly select provider.
Fixed the issue and:
- Add new tests to improve coverage of different cases for getProvider and determineProvider
- Create facility to allow testing of survey interactive workflow
- Create fake RootCmd to prevent tests affecting each other due to manipulation of the flags.

Fix loading of selected provider, add more test cases for getProvider

---

src/cmd/cli/command/commands.go

Hides mirrored commands (`up`, `down`, `restart`) from the top-level root menu, as per linked issue.
Details:
- the commands still work as they did before, just hidden
- `up`, `down`, and `restart` still show up in the `defang compose` menu
- `RestartCmd` at top-level is replaced with `makeComposeRestartCmd()` 
Fixes #912

Hide mirrored cmds from top-level menu

---

src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/cli/client/byoc/do/byoc.go
src/pkg/cli/client/byoc/gcp/byoc.go

- Added an optional "NO_COLOR" key in the environment for the cloud providers
- This key will exist if `term.StdoutCanColor()` is false (i.e. if color is not enabled in the CLI)
Fixes #921

Add Pulumi "NO_COLOR" env for BYOC

---

src/cmd/cli/command/version.go
src/pkg/cli/compose/constants.go
src/pkg/cli/compose/convert.go
src/pkg/cli/compose/fixup.go
src/pkg/cli/compose/validate_test.go
src/pkg/cli/compose/validation.go
src/pkg/quota/service_test.go
src/tests/postgres/compose.yaml
src/tests/postgres/compose.yaml.fixup
src/tests/postgres/compose.yaml.golden
src/tests/postgres/compose.yaml.warnings
src/tests/redis/compose.yaml
src/tests/redis/compose.yaml.fixup
src/tests/redis/compose.yaml.golden
src/tests/redis/compose.yaml.warnings

Replace #918: make ports optional for managed services.
Ideally we'd do this "fixup" in the Pulumi deployment code.

Make ports optional for managed redis/postgres

---

src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/cli/client/byoc/do/byoc.go
src/pkg/cli/client/byoc/gcp/byoc.go

at a glance, I thought these vars referred to values from a previous defang invocation, but it turns out they are for the _current_ invocation, so I think removing the "last" prefix will help a future reader to avoid that confusion.
https://github.com/DefangLabs/defang/pull/923#discussion_r1890983036

remove "last" prefix from byoc client attrs

---

src/cmd/cli/command/compose.go
src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/cli/client/mock.go
src/pkg/cli/tail.go
src/pkg/cli/tail_test.go
src/pkg/clouds/aws/ecs/event.go
src/pkg/clouds/aws/ecs/logs.go
src/pkg/utils.go
src/pkg/utils_test.go

Sometimes AWS CW Tail API returns `SessionStreamingException`. This PR ensures we automatically retry the Tail in that case.
```
Error: SessionStreamingException: Internal Streaming Error Encountered in Live Tail Session: [f364f055-47b8-41ee-a298-88dfae6e802f] for Account: [861988606655]
```

Retry Tail on SessionStreamingException

---

src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/cli/client/byoc/gcp/stream.go
src/pkg/clouds/aws/ecs/logs.go
src/pkg/errors.go

This fixes a regression caused by #914 where "defang up" would always fail with `ErrDeploymentFailed` even when CD exited with 0, ie. success.

fix: don't return ErrDeploymentFailed for clean CD exit

---

src/cmd/cli/command/commands.go
src/cmd/cli/command/compose.go

Make `defang tail` behave similar to `defang ps` etc. by using `LoadProjectNameWithFallback`.

Fix tail without project

---

src/cmd/cli/command/version.go

When GitHub API gets throttled the CLI just prints `Error: 403 Forbidden`, without much context. This PR prints the actual error message (if available) for better diagnosis.

Better error message when GitHub REST API fails

---

src/cmd/cli/command/cd.go
src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/cli/client/byoc/gcp/byoc.go
src/pkg/clouds/do/appPlatform/setup.go

Failures in CLI:
```
$ defang cd cancel --project-name nextjs -Pdigitalocean
* Using DigitalOcean provider from command line flag
* Running CD command "cancel" in project "nextjs"
Error: invalid image:
```
AWS:
```
$ AWS_PROFILE=defang-lab defang cd cancel --project-name nextjs -Paws
* Using AWS provider from command line flag
* Running CD command "cancel" in project "nextjs"
Waiting for CloudFormation stack defang-cd to be updated...
Error: waiter state transitioned to Failure
```
Getting empty image URL even though I’m pro. Seems that cancel and refresh didn't check `canIUse`. 
Missed these two commands in #929

Fix cd cancel and cd refresh

---

src/cmd/cli/command/compose.go
src/pkg/cli/debug.go
src/pkg/cli/debug_test.go

Fixes panic when replying `N` to debug prompt:
```
$ defang compose up
! Unable to load project: yaml: line 2: could not find expected ':'
? Choose a cloud provider: defang
* Using Defang Playground provider from interactive prompt
! yaml: line 2: could not find expected ':'
? Would you like to debug the deployment with AI? No
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10214868c]
goroutine 1 [running]:
main.main.func1()
/Users/llunesu/dev/defang/src/cmd/cli/main.go:19 +0x144
panic({0x102aae920?, 0x104b27f10?})
/nix/store/rfcwglhhspqx5v5h0sl4b3py14i6vpxa-go-1.22.7/share/go/src/runtime/panic.go:770 +0x124 …
```

Fix debug panic

---

src/pkg/cli/client/byoc/aws/byoc.go

fixes #968  
Fix panic when using debug command
https://github.com/DefangLabs/defang/issues/968

populate byoc client with task arn used by client to extract information

---

src/pkg/cli/composeDown.go
src/pkg/cli/composeUp.go
src/pkg/cli/delete.go

#fixes 970 
panic occurs in CLI when GetDelegateSubdomainZone() returns error, but we still try to reference as if it there was no error. Fix to exit command if error is found.
#970

fix panic if delegate domain is not returned

---

src/pkg/cli/client/grpc.go
src/pkg/cli/client/grpc_logger.go

If you get a network error when invoking a CLI command, it can be difficult to understand which request caused it. This PR introduces a grpc client "interceptor" (like a middleware), which logs outgoing requests. We print the type of the request as well as a json marshalled string of the payload to stdout when `--debug` mode is enabled.
Here's an example session:
```
defang whoami --debug
- Reading access token from file /Users/llunesu/.local/state/defang/fabric-prod1.defang.dev
- Using tenant default for cluster fabric-prod1.defang.dev:443
- fabricClient /io.defang.v1.FabricController/WhoAmI null
- fabricClient /io.defang.v1.FabricController/GetVersion null
- Fabric: v0.6.0-296-g4237cb43 CLI: development CLI-Min: v1.0.0
- tracking event "WHOAMI INVOKED": [{args []} {err <nil>} …
```

Log fabric grpc requests in debug mode

---

src/cmd/cli/main.go
src/pkg/http/client.go
src/pkg/http/post.go
src/pkg/http/post_test.go
src/pkg/logs/slog.go

The `PostForValues` helper did not check the response status. The default HTTP client was also logging to `term`, even though its being used in the backend which shouldn't use the `term` package.

Check response status in PostForValues

---

src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/clouds/aws/ecs/logs.go

Customer was trying to use `defang debug` but got gRPC error that the payload was too large. We truncate the logs on the backend to fit in the LLM context, but the CLI needs to make sure it's within the gRPC limits.

Truncate debug query

---

src/pkg/cli/composeDown_test.go

- Create CLI tests for `composeDown.go`
- https://github.com/DefangLabs/defang/blob/main/src/pkg/cli/composeDown.go
- Skip a test for `InteractiveComposeDown` because it needs to be interactive action. To test it, it looks necessary to split the logic of `survey`.
- https://github.com/DefangLabs/defang/blob/main/src/pkg/cli/composeDown.go#L70-L85
#983

Create test for composeDown

---

src/pkg/cli/configDelete_test.go
src/pkg/cli/configSet_test.go

- Create tests for
- [configDelete](https://github.com/DefangLabs/defang/blob/main/src/pkg/cli/configDelete.go)
- Add test cases for
- [configSet](https://github.com/DefangLabs/defang/blob/main/src/pkg/cli/configSet.go)
https://github.com/DefangLabs/defang/issues/988

Create tests for configSet and configDelete

---

src/pkg/cli/client/byoc/gcp/byoc.go
src/pkg/cli/client/byoc/gcp/query.go

Do not add execution name query when there is none, otherwise when we do defang tail, gcp log query would have a OR clause for cloudrun jobs without any other constraint, which could show cloudrun logs from other projects.

Do not add execution name query when there is none

---

src/pkg/cli/client/byoc/aws/byoc.go

- The current main branch built command can't run `defang tail`.
```bash
./defang tail --since=2025-02-14T00:20:43.964Z --type=RUN --project-name=ecs-yuta-cluster
* Showing logs since 2025-02-14T00:20:43.964Z ; press Ctrl+C to stop:
* Using AWS provider from stored preference
Error: https response error StatusCode: 400, RequestID: 9e7ad05f-ae4d-4da2-8907-0d7c5566bc7d, InvalidParameterException: Invalid filter pattern: Invalid character(s) in term '""'
```
- If adding qoutes to filter with a empty string, `"\"\""` will be returned, which is invalid as cloudwatch filter pattern
#1008

Fix: skip quote in the case that "filter" is empty

---

src/pkg/cli/compose/context.go
src/pkg/cli/compose/context_test.go
src/testdata/alttestproj/ignored.Dockerfile

Keep default `.dockerignore` in sync with https://github.com/DefangLabs/pulumi-defang/pull/51

Ignore Dockerfile/Compose files by default

---

src/pkg/cli/client/byoc/gcp/byoc.go
src/pkg/clouds/gcp/cloudrun.go

Removing need for GCP execution name when getting debug logs
[
](https://github.com/DefangLabs/defang/issues/941)

remove need to get execution name

---

src/pkg/cli/client/byoc/baseclient.go
src/pkg/cli/client/playground.go
src/pkg/cli/client/provider.go
src/pkg/cli/subscribe.go
src/pkg/cli/subscribe_test.go

Current local unit tests is block for 10s for the retry test, as we hard code the delay before retry in subscribe.go to be 1s between each of the 5 reties. In this PR the delay logic is pushed to the provider interface, so int he test, we can have a minimum delay, reduce the local test time by 10s
No issue.

Create interface to allow retry unit test to be faster

---

src/cmd/cli/command/compose.go

to make sure AI debugger is triggered when cd exit abnormally
When cd exit abnormally an ErrDeploymentFailed is returned, but the current code will only handle context cancelled with ErrDeploymentFailed error, preventing the AI debugger from starting.
This code should be refactored:
- Current logic is convoluted, difficult to read
- Logic of handling no permission to read log should not be in compose.go

HACK: do not return ErrDeploymentFailed returned from tail

---

src/pkg/cli/client/byoc/gcp/byoc.go

As CD logs often are incomplete due to the delayed availability of logs in the gcp logging tail API, probably due to aggregation.
Increase the delay after cd exit to 3s for gcp

Increase the delay after cd exit to 3s for gcp

---

src/pkg/cli/client/byoc/aws/validation_test.go
src/pkg/cli/compose/fixup.go
src/testdata/alttestproj/compose.yaml.fixup
src/testdata/gpu/compose.yaml
src/testdata/gpu/compose.yaml.golden
src/testdata/sanity/compose.yaml.fixup
src/testdata/testproj/compose.yaml.fixup

No need to explicitly set replicas to 1 since we do it in CD.
Fixes #1017

Remove replicas fixup

---

src/pkg/cli/client/client.go
src/pkg/cli/client/grpc.go
src/pkg/cli/client/playground.go
src/pkg/cli/client/playground_test.go
src/pkg/cli/configList_test.go
src/pkg/cli/connect.go
src/pkg/cli/destroy_test.go
src/pkg/cli/getServices_test.go
src/pkg/cli/whoami_test.go

This PR extracts a mockable `FabricClient` interface to support unit testing in the V1 Defang Pulumi Provider: https://github.com/DefangLabs/pulumi-defang/pull/54
In order to do this, I needed to avoid accessing data attributes directly, so I implemented `GetTenantName` and `GetController`.
https://github.com/DefangLabs/pulumi-defang/pull/54

expose FabricClient interface

---

.vscode/extensions.json
src/cmd/cli/command/compose.go
src/cmd/cli/command/compose_test.go
src/cmd/cli/command/deploymentinfo.go
src/cmd/cli/command/deploymentinfo_test.go
src/pkg/cli/composeUp.go
src/pkg/cli/composeUp_test.go

This PR does the following:
1. factor out `cli.WaitAndTail` to encapsulate the logic for setting up a Tail stream for monitoring a deployment. That way, the new V1 Defang Pulumi Provider in https://github.com/DefangLabs/pulumi-defang/pull/54 can tail logs after initiating a deployment.
3. move the following helpers (and their tests) from the `command` package, to the `cli` package. This way, they are co-located with `cli.TailUp`:
* `isManagedService`
* `splitManagedAndUnmanagedServices`
https://github.com/DefangLabs/pulumi-defang/pull/54

factor out cli.WaitAndTail for use by new pulumi provider

---

src/pkg/cli/client/playground.go
src/pkg/cli/client/provider.go
src/pkg/cli/composeUp.go

The new pulumi provider needs to be able to call `GetProjectUpdate` on the Provider client, so this PR adds that method to the public interface. It is not implemented for playground—only for BYOC providers.
https://github.com/DefangLabs/pulumi-defang/pull/54

add GetProjectUpdate to Provider interface

---

.vscode/settings.json

This PR configures vscode to use `golangci-lint` to present lint warnings inline. We already use `golangci-lint` in git hooks, so adding this configuration will further "shift left" these lint warnings.

Configure VSCode so that golangci-lint warnings are visible inline

---

src/Makefile

I was trying to test the cli locally, but running `make -C src install` was not replacing the installed build. I was not making commits between each test, so the version number was staying the same.
This PR makes the following changes to the `src/Makefile`:
* the `$(BINARY_NAME)` target depends on all of the go source files.
* create a phony `build` target for convenience
* remove `test` dependency from `build` target to `install` target. Sometimes I want to run `make build` before committing to fixing broken tests.

Ensure dirty revision builds

---

src/cmd/cli/command/commands.go

Added `IsUpgradeCommand()` to check if a user is already running `defang upgrade` before printing the upgrade warning message.
Fixes #1043

Avoid upgrade message when running upgrade command

---

src/cmd/cli/command/commands.go

Currently, there is an upgrade hint (different from a warning) that is shown randomly (1/10 chance) when a user runs a command. If they are running the `defang upgrade` command, we should suppress this hint in all cases.
This PR will suppress the hint on `defang upgrade`, and use a `hideUpdate` variable instead of `os.Setenv` to achieve this. 
Related to #1045

Hide upgrade hints using a variable instead of os.Setenv

---

src/cmd/cli/command/commands.go

I had forgotten one dash and was confused why I didn't see any logs when I did `defang tail -project-name defang`. I figured it's not uncommon so I added a warning for it.

Ask for confirmation for sus project names

---

src/.goreleaser.yml

Enable creation of winget-pkg PR to be automatically created on release. Definition was already existing. Was able to make a draft release PR, this bypass the need for the Defang's fork of the winget-pkg repo.
[link](https://github.com/DefangLabs/defang/issues/950)

enable winget-pkg manifest creation and PR

---

src/cmd/cli/command/cd.go
src/cmd/cli/command/commands.go
src/cmd/cli/command/compose.go
src/pkg/cli/tail_test.go

Introduces a UTC flag to display timestamps in UTC for various CLI commands.
`time.Local = time.UTC` sets the default local timezone for the Go program to UTC. By default, Go uses the system's local timezone for operations involving time.Local. This line overrides that behavior, forcing all operations that rely on time.Local to use UTC instead.
Flag: --utc
Commands:
- compose up and up
- compose down and down
- compose tail and logs
- all cd commands
#1053

Adds UTC timestamp option to CLI commands

---

.github/workflows/go.yml
src/.goreleaser.yml

This reverts commit d9e2ac5.## Description
Enable creation of winget-pkg PR to be automatically created on release. Definition was already existing. Was able to make a draft release PR, this bypass the need for the Defang's fork of the winget-pkg repo.
fixes #950

Reapply "enable winget-pkg manifest creation and PR (#1054)" (#1064)

---

src/cmd/cli/command/commands.go

* `modelId` global was overwritten with empty string

fix: DEFANG_MODEL_ID env wasn't used

---

src/.goreleaser.yml

On release of now CLI, have goreleaser make a PR rather than a draft, now that we have confirmed the mechanics of making windows releases.
fixes #950

make PR instead of draft PR on winget repo

---

src/cmd/cli/command/commands.go
src/cmd/cli/main.go
src/pkg/cli/connect.go
src/pkg/cli/debug.go
src/pkg/track/track.go

Track ctrl-c interrupt in main goroutine to avoid WaitGroup panic
What must have happened is that we’re calling FlushAllTracking at the end of main but during the Wait another event happened in some go routine, so the WaitGroup went from 0->1 causing the panic.

fix: use new NotifyContext helper

---

src/pkg/cli/compose/loader.go

Making this error message about env vars being unresolved more specific to clarify that it was not resolved locally.

clarify message about unresolved env vars

---

src/pkg/cli/compose/context.go

Changes:
- err := writeDefaultIgnoreFile(root) -> dockerignore, err = writeDefaultIgnoreFile(root) 
By doing this we can make sure that the caller knows the name of the file that was written, which make it more explicit 
and easier to understand. 
- I also changed term.Info() to term.Warn() to make the text popout.
- Added a constant
This is tech debt from the #1068 
#1015

Return file name from function

---

src/.goreleaser.yml

After exploring many options and a lot of discussion we have decided to just remove the support for GoReleaserbot can generate and publish a nix derivation.
The cons outweight the pros to keep the Nix support for goreleaser. 
For more context please read the attached issue below.
#24

Remove support for Goreleaser to publish a nix derivation

---

src/cmd/cli/command/cd.go
src/cmd/cli/command/commands.go
src/cmd/cli/command/compose.go
src/pkg/cli/bootstrap.go
src/pkg/cli/composeUp.go
src/pkg/cli/debug.go
src/pkg/cli/debug_test.go
src/pkg/cli/tail.go

Rename Etag to Deployment for internal structs
Extracted from https://github.com/DefangLabs/defang/pull/1033

Rename Etag to Deployment for internal structs

---

src/cmd/cli/command/cd.go
src/cmd/cli/command/commands.go
src/cmd/cli/command/compose.go
src/cmd/cli/command/deploymentinfo.go
src/cmd/cli/command/deploymentinfo_test.go
src/pkg/cli/bootstrap.go
src/pkg/cli/composeUp.go
src/pkg/cli/debug.go
src/pkg/cli/debug_test.go
src/pkg/cli/deploymentsList.go
src/pkg/cli/deploymentsList_test.go
src/pkg/cli/getServices.go
src/pkg/cli/getServices_test.go
src/pkg/cli/tail.go

Use `term.Table` to print deployed services with their id, name, status, endpoints, and domain names.

Print deployment results as a table

---

pkgs/defang/default.nix

Using `lib.warn` to issue a warning during evaluation.
Goreleaser nix rule was commented in #1078

Deprecate the old Nix derivation

---

src/pkg/cli/client/byoc/aws/byoc.go

I spent a lot of time trying to use `DEFANG_PULUMI_DIR` today before eventually digging up the source code and realizing that it was ignored unless you also passed `--debug`. 🤦  This change lets you use `DEFANG_PULUMI_DIR` regardless of the `debug` flag.

debug with DEFANG_PULUMI_DIR

---

src/pkg/cli/configList_test.go
src/pkg/cli/deploymentsList_test.go
src/pkg/cli/getServices_test.go
src/pkg/term/colorizer.go
src/pkg/term/table.go

Small UX issue. This PR makes the headers of any tables bold (when that's allowed by the output).

Make table header bold

---

src/cmd/cli/command/commands.go

`defang token` does not need to load a project, so we can skip the loader (and the cloud provider picker).

fix: defang token does not need to load the project

---

src/pkg/cli/login.go
src/pkg/cli/token.go
src/pkg/github/auth.go

There was an issue with MCP login not trigger,
because of the auth github flow. The problem
was that the auth flow was not being triggered
because of the else condtion. There was no need
for the else condition.

Fix github auth flow for MCP

---

src/cmd/cli/command/commands.go
src/pkg/cli/login.go
src/pkg/cli/login_test.go
src/pkg/github/auth.go
src/pkg/mcp/tools/login.go

The higher level function(InteractiveLogin)->
(githubAuthService.login) -> GitHubAuth interface
-> (githubAuthService.login) -> github.StartAuthCodeFlow need the prompt bool to be pass all the way down.
I also reverse the prompt logic because I felt it
was more intuitive to have the prompt like this.

Found that auth was not following prompt bool

---

src/pkg/mcp/setup.go

I notice after the build that when I called
npx it did not update my version. So to make
sure that the latest version is used, I
added a tag to the setup.go file.

Add latest tag to setup

---

src/cmd/cli/command/mcp.go
src/pkg/mcp/tools/deploy.go
src/pkg/mcp/tools/destroy.go
src/pkg/mcp/tools/login.go
src/pkg/mcp/tools/services.go
src/pkg/mcp/tools/tools.go

When we were making a call to the grpc client, we were not refreshing the token before making the call. This caused the client was not reconstructed with the new token. So now with every tool call we just remake the grpc client with the new token.

Fix token refresh issue with grpc client

---

src/pkg/mcp/README.md

Updates the `README.md` file in `/src/pkg/mcp` to have `defang@latest` in the installation commands, consistent with [PR #216 in /defang-docs repo](https://github.com/DefangLabs/defang-docs/pull/216/)
N/A

Add @latest to mcp readme

---

pkgs/npm/.npmignore
pkgs/npm/mocha.ts
pkgs/npm/package-lock.json
pkgs/npm/package.json
pkgs/npm/src/cli.ts
pkgs/npm/src/clilib.ts
pkgs/npm/test/clilib.spec.ts
pkgs/npm/tsconfig.json
pkgs/npm/tsconfig.test.json

- fix for unzipping windows defang.exe failure (issue discovered during mcp testing)
- fix for handling errant defang binary in npx cache
- fix for "npm run build" and "npm run test" so no tinkering is need to get one or the other to run
- fixed/updated tests

fix for windows npx

---

.golangci.yaml
pkgs/defang/cli.nix
src/go.mod
src/go.sum

This PR replaces spf13/cobra with the DefangLabs fork so that it can print command aliases in the generated markdown files for CLI docs.
https://github.com/DefangLabs/defang-mvp/issues/1550

Print command aliases for generated CLI docs

---

src/pkg/cli/compose/fixup.go

When x-defang-llm is defined for a service, it would always override the port settings, making it port 80 and mode set to host. This should only be a default, not an override.
None

Fix: only override x-defang-llm port settings if not set

---

README.md
src/cmd/cli/command/cd.go
src/cmd/cli/command/commands.go
src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/cli/client/byoc/do/byoc.go
src/pkg/cli/client/byoc/gcp/byoc.go

Adding `--json` to the CD commands, which sets `DEFANG_JSON` for the CD task.
For #1110

Add --json to cd command

---

src/pkg/cli/cert.go
src/pkg/cli/client/byoc/baseclient.go
src/pkg/cli/client/byoc/common.go
src/pkg/dns/check.go
src/pkg/dns/utils.go
src/pkg/dns/utils_test.go

Move DNS helpers to dns package

---

src/cmd/cli/command/commands.go
src/cmd/cli/command/compose.go
src/pkg/term/colorizer.go
src/pkg/term/colorizer_test.go

Show all unique warnings at the end of CLI execution so users are aware of any potential issues. Logs may have flown by too fast for users to see.
Address part of #1084

show warnings at end

---

.github/workflows/go.yml

PR test failures were triggering Slack notifications. This was because I had misunderstood how `needs` works, so the `on-release-failure` was still triggered, even though we weren't doing a release.

Only send Slack notification for main or tag

---

src/pkg/cli/compose/loader.go

When you do for example `defang deployments list` outside a project folder, the error message reads `Error: no compose.yaml file found`, which is correct but forgets to mention that you only need that file when you don't specify `--project-name`. 
This applies to other commands that need project name, but don't actual need the Compose project. This PR will show `no --project-name specified and no compose.yaml file found`.

Improve error when project name is needed

---

src/pkg/cli/compose/fixup.go
src/pkg/cli/compose/validation.go
src/testdata/llm/Dockerfile
src/testdata/llm/compose.yaml
src/testdata/llm/compose.yaml.fixup
src/testdata/llm/compose.yaml.golden
src/testdata/llm/compose.yaml.warnings

For openai-access-gateway we want to set a default port configuration if one is not defined.
Also allow in playground.
None - this is a continuation of PR #1138

handle x-defang-llm fixup only openai-access-gateway image

---

src/cmd/cli/command/commands.go
src/cmd/cli/command/compose.go
src/pkg/term/colorizer.go
src/pkg/term/colorizer_test.go

Most commands have very little output, so it's not useful to print the warnings once more at the end of the command. In particular, it's the `compose up` command that has tons of output, such that the original warnings have scrolled off the screen.
This PR also fixes the unnecessary repetition of the "Please log in" warning.

Only repeat warnings for compose up

---

src/pkg/mcp/setup.go

- If the JSON unmarshal succeeds, but the file on disk does not contain the MCPServers field (or it is null in the JSON), then after unmarshal, config.MCPServers will be nil. This is a subtle bug: If the config file exists and is missing the MCPServers field, unmarshal will not set it, leaving it as nil.
- Then, when I try to assign to config.MCPServers["defang"], causing the panic.
- Solution: map instantiation guard before assignment
Test are written in a different PR

config is not initialized after JSON unmarshal succeeds

---

src/pkg/cli/upgrade.go

By default, `brew upgrade defang` doesn't upgrade any already installed version of `defang` because it's a cask, and the user will have to first do `brew update`, but adding `-g` makes the upgrade "greedy" and will update the cask (and the tool).

Add -g to brew upgrade

---

src/pkg/cli/client/byoc/gcp/byoc.go

So deployment table will track the gcp project ID instead of email.

Use project id as AccountID for gcp instead of email

---

pkgs/defang/cli.nix
src/go.mod
src/go.sum
src/pkg/cli/compose/fixup.go
src/pkg/cli/compose/validation.go
src/pkg/cli/compose/validation_test.go
src/testdata/provider/compose.yaml
src/testdata/provider/compose.yaml.fixup
src/testdata/provider/compose.yaml.golden
src/testdata/provider/compose.yaml.warnings

When we detect a Docker Model Runner `provider:`, we transparently replace that with the `openai-access-gateway`, so that the project works as-is! This still requires changing the model name, local vs cloud, but the future "model map" can take care of that.

Use openai-access-gateway for model runner

---

src/pkg/cli/compose/fixup.go
src/testdata/provider/compose.yaml.fixup

Follow up from #1161: add the provider pseudo-service, and any service that depends on it, to a private network. This makes it safe to disable access-gateway auth by setting `OPENAI_API_KEY=""`. 
View diff w/o whitespace.

Put provider in private network

---

src/cmd/cli/command/mcp.go
src/cmd/cli/main.go
src/cmd/cli/setuidgid_other.go
src/cmd/cli/setuidgid_windows.go
src/pkg/cli/client/state.go
src/pkg/cli/client/state_other.go
src/pkg/cli/client/state_windows.go
src/pkg/cli/login.go
src/pkg/cli/login_test.go
src/pkg/mcp/resources/resources.go
src/pkg/mcp/setup.go

Set the process's UID and GID based off of the ownership of `$HOME`. This ensures we don't create token/log files with permissions that the user can't access, for example when `defang` is run as `root` through `sudo`.
Fixes #1176

Drop UID/GID based on HOME perms

---

pkgs/defang/cli.nix
src/cmd/cli/command/commands.go
src/cmd/cli/command/compose.go
src/cmd/cli/command/estimate.go
src/cmd/cli/command/estimate_test.go
src/go.mod
src/go.sum
src/pkg/cli/bootstrap.go
src/pkg/cli/client/grpc.go
src/pkg/cli/preview.go
src/pkg/cli/tail.go
src/pkg/money/money.go
src/pkg/money/money_test.go

Add a new command `defang estimate` which does the following:
1. Load the project from the current working directory, or from `-f`
2. Run `pulumi preview` in JSON format mode in a cd task in the user's cloud account and keep a buffer of the json-formatted pulumi preview operation log lines. (Note: this requires the user to provide their cloud account credentials. In a followup, we will remove this requirement and enable the possibility to run previews in our cloud accounts.)
3. Pass the json-formatted pulumi operations to fabric as a byte array so that fabric can estimate the AWS workload
* https://github.com/DefangLabs/defang/pull/1173
* https://github.com/DefangLabs/defang-mvp/pull/1768
* https://github.com/DefangLabs/defang-mvp/pull/1770

Add defang estimate command

---

src/cmd/cli/command/commands_test.go
src/pkg/cli/client/byoc/baseclient.go
src/pkg/cli/client/mock.go
src/pkg/cli/client/playground.go
src/pkg/cli/client/projectName.go
src/pkg/cli/client/projectName_test.go

When doing `defang config set` to a clean account (and outside of a project dir), the error was not clear:
> Error: StackNotFoundException: Stack with id defang-cd does not exist
This happens because secret/config names are scoped per project, but when we're outside a project, we try to fetch the (single) deployed project from the cloud, which (on AWS) requires an S3 bucket from the CloudFormation stack.
This PR fixes this, by including any previous (loading) error as well:
> Error: no --project-name specified and no compose.yaml file found and no cloud projects found: StackNotFoundException: Stack with id defang-cd does not exist

Fix error for config set to clean account

---

src/cmd/cli/command/commands.go
src/cmd/cli/command/compose.go

Fix regression in `compose up` where we no longer ask for interactive `compose down`.

Fix interactive down on max projects

---

src/pkg/cli/compose/fixup.go
src/testdata/provider/compose.yaml.warnings

In #1190 I moved the Docker `provider:` handling to be before the DNS fixup, but the existing provider code would already add the user's tenant ID to the service names (for Playground), so by moving that fixup code up, the DNS service name replacement happened twice. This broke the `managed-llm-provider` sample.

Fix provider fixup: adjust DNS once

---

src/pkg/cli/cert.go

This fixes ACME cert gen for `default` network aliases (same as backend):
```
services:
app:
image: nginx
domainname: demo.example.com
networks:
default:
aliases:
- www.example.com
```

Generate cert for default aliases too

---

src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/cli/client/byoc/baseclient.go
src/pkg/cli/client/byoc/gcp/byoc.go

This is in preparation for #1191 so we can update Pulumi without having to update the CLI.
```
$ curl -HAuthorization:"bearer $(cat ~/.local/state/defang/$DEFANG_FABRIC)"  -Hcontent-type:application/json https://$DEFANG_FABRIC/io.defang.v1.FabricController/CanIUse -d'{"provider":4}'
{"cdImage":"532501343364.dkr.ecr.us-west-2.amazonaws.com/cd:public-gcp-v0.6.0-576-gf5b76e67", "gpu":true, "allowScaling":true, "pulumiVersion":"3.148.0"}%    
```

Use Pulumi Version from Fabric

---

src/pkg/cli/client/playground.go

This is what caused the issue in #1085 but the fix for older CLIs is in the backend.

Pass project name to DeleteSecrets

---

src/pkg/cli/client/byoc/gcp/stream.go

So the grpc stream is properly closed

Close the tailer in gcp server stream Close() method

---

src/pkg/cli/client/byoc/aws/byoc.go
src/pkg/cli/client/byoc/do/byoc.go
src/pkg/cli/client/byoc/gcp/byoc.go

New Pulumi CLI appears to print a note about their Copilot. Not sure whether this gets triggered only when using Pulumi Cloud, but it's potentially confusing so let's disable it. Env var was listed on https://www.pulumi.com/docs/iac/cli/environment-variables/

Disable Pulumi copilot

---

src/pkg/cli/tail.go

Cli currently exits fast when it is not running in verbose mode. This is due to an early exit condition introduced in [PR #1169 Add defang estimate command](https://github.com/DefangLabs/defang/commit/3b05b03fa7cb7748b9c6cfb6e7da8a8c6bb68234#diff-eaaea9856777a2f5870fca35a2c52aef840f045c6558b3b56def7132d9125e95L351)

Fix cli early exit when not running in verbose mode

---

src/cmd/cli/command/compose.go
src/pkg/cli/composeUp_test.go
src/pkg/cli/subscribe.go
src/pkg/cli/subscribe_test.go
src/pkg/cli/tailAndMonitor.go

After `compose up` we print the state of all services, but this table is fake: it always shows COMPLETED. This is now fixed to show the actual latest states.

Print real service state

---

src/pkg/cli/compose/fixup.go
src/testdata/provider/compose.yaml
src/testdata/provider/compose.yaml.fixup
src/testdata/provider/compose.yaml.golden

@raphaeltm was trying to deploy this configuration:
```yaml
llm:
provider:
type: model options:
model: us.amazon.nova-premier-v1:0
x-defang-llm: true
environment:
DEBUG: "true" # this gets replaced by the current CLI version
```
But the previous CLI code was overwriting the environment. This change should allow `DEBUG: "true"` to remain in the env even if we set `OPENAI_API_KEY=""`
This PR will also allow the user to set `OPENAI_API_KEY` to something else

avoid truncating access gateway env

---

src/cmd/cli/command/estimate.go

In order to avoid requiring cloud credentials to generate an estimate, we will now run the deployment preview on the defang provider (playground). This should also help reduce latency as we already have a cd task running and we won't have to wait for it to spin up.
There is a little subtlety here, because we handle the `-P, --provider` flag passed by the user differently in this case than we do in other commands. Instead of running the preview on the specified provider, we will always run the preview on the Defang provider, and we will always generate the estimate with fabric, but we will still use the passed provider name to determine the deployment and estimation target.
https://github.com/DefangLabs/defang-mvp/pull/1836

Always run estimate previews on defang provider

---

src/pkg/cli/bootstrap.go
src/pkg/cli/client/provider.go
src/pkg/cli/tail.go
src/pkg/cli/tailAndMonitor.go
src/pkg/cli/waitForCdTaskExit.go

Handle GCP transient errors and retry for waiting for service states and cd task when there is transient error

Handle GCP transient errors and retry for waiting for service states and cd task when there is transient error

---

src/cmd/cli/command/estimate.go
src/cmd/cli/command/mode.go
src/pkg/mcp/tools/estimate.go

Added support for MCP deployment modes (dev and prod)

added support for mcp estimate deployment modes

---

src/pkg/cli/tail.go

So cli will do a retry when connection reset happens.

Consider Connection Reset and Connection Aborted as transient error

---

src/cmd/cli/command/commands.go

`defang token` accepts `--org=…` but did not pass it to the RPC call.

Pass org to Token rpc

---

src/pkg/cli/login.go

Adding the `tail` scope to the noninteractive github login token scope so that we can support estimates in CI. We may roll this back in the future and make this opt-in
Depends on https://github.com/DefangLabs/defang-mvp/pull/1947

add tail scope to github actions workflows

---

src/cmd/cli/command/estimate.go

Running `defang estimate -P gcp` should run the preview in a gcp account if gcp credentials are available.
* https://github.com/DefangLabs/defang-mvp/pull/1915

Allow gcp estimate preview provider

---

src/cmd/cli/command/deploymentinfo_test.go
src/cmd/cli/command/estimate_test.go
src/pkg/cli/configList_test.go
src/pkg/cli/deploymentsList_test.go
src/pkg/cli/estimate.go
src/pkg/cli/getServices_test.go
src/pkg/term/table.go

I've seen many CLIs (like `docker`) that use UPPERCASE table headers, which is nice when we don't have an ANSI-capable terminal.
```
SERVICE      DEPLOYMENT    PUBLICFQDN                                     PRIVATEFQDN                  STATUS
redis        leozagfrmcdq                                                 redis.docs-chatbot.internal  PROVISIONING
llm          leozagfrmcdq                                                 llm.docs-chatbot.internal    PROVISIONING
app          leozagfrmcdq  app.docs-chatbot.commit111.defang.app                                       PROVISIONING
discord-bot  leozagfrmcdq  discord-bot.docs-chatbot.commit111.defang.app                               PROVISIONING
```

uppercase table headers

---

src/.goreleaser.yml

The current tag for nightly builds is "devel", rename to "nightly" to be better descriptive.
fixes #1312

update nightly tag to "nightly" rather than "devel"

---

src/pkg/cli/client/mock.go
src/pkg/cli/compose/fixup.go
src/pkg/cli/compose/loader.go
src/pkg/cli/compose/validation_test.go
src/testdata/configoverride/compose.yaml.warnings
src/testdata/fixupenv/compose.yaml.fixup
src/testdata/interpolate/compose.yaml
src/testdata/interpolate/compose.yaml.fixup
src/testdata/interpolate/compose.yaml.golden
src/testdata/interpolate/compose.yaml.warnings
src/testdata/models/compose.yaml.fixup
src/testdata/mongo/compose.yaml.fixup
src/testdata/provider/compose.yaml.fixup
src/testdata/testproj/compose.yaml.fixup

Having a "eponymous" env var would trigger a warning:
```yaml
services:
interpolate:
image: blah
environment:
VAR1: ${VAR1}
```
```
! service "interpolate": environment variable(s) ["VAR1"] overridden by config
```
…which was what was intended all along, so this warning doesn't add anything.
In addition to that change, the code used a difference mock provider for validation (`.warnings` file) and fixup testing (`.fixup` file), which was confusing, so now using a single mock.

fix: no 'overridden by config' warning for X=${X}

---

src/cmd/cli/command/commands.go
src/cmd/cli/command/mcp.go
src/pkg/mcp/setup.go

The mcp.json used by vscode/insiders has changed format on how to declare servers. This fix address the change in format.
fixes #1317

fix for vscode mcp setup - location of settings changed with latest vcode

---

src/pkg/mcp/setup.go

Changed `insiders` ---> `code-insiders` to match the terminal binary name.

Update vscode insider alias to match CLI name

---

src/cmd/cli/command/compose.go
src/pkg/cli/client/byoc/baseclient.go
src/pkg/cli/compose/context.go
src/pkg/cli/compose/context_test.go
src/pkg/cli/debug.go

Use AI debugger to handle common "compose up" errors (like IAM permissions). For example, when you get the AssumeRole error:
> =================
> Debugging Summary
> \=================
> The log shows an AWS IAM permission error when trying to access Route 53 DNS services. The application is attempting to assume an IAM role (dnsadmin-39a19c3) but lacks the necessary permissions to do so.
> -------------------
> Issue #1
> -------------------
> The error occurs because the service is trying to use a DNS role (arn:aws:iam::258338292852:role/dnsadmin-39a19c3) that it doesn’t have permission to assume. This is likely because either the role doesn’t exist or the service doesn’t have the correct permissions to assume it. If DNS configuration is not needed, you can remove the x-defang-dns-role …

Call debugger on composeUp errors

---

src/cmd/cli/command/commands.go

Running common editors like `vim` as a new process won't work, because they'd start in the background without TTY.
No doc change since README wasn't changed in #1354 https://github.com/DefangLabs/defang/blob/b402051980254b00d9f53f16eba8b04d917f0e13/README.md#L128 
Regression from #1354

revert: use DEFANG_EDITOR instead of EDITOR

---

src/pkg/cli/compose/context.go
src/pkg/cli/compose/context_test.go

We added both .zip and tar.gz extension to the end of the archive URL. We need to support .zip extension because GCP cloudbuild would reject it.  
Going to do a manual test first.

Need .zip for GCP cloudbuild railpack

---

flake.nix
src/Dockerfile
src/Makefile

This address the build failure in https://github.com/DefangLabs/defang/actions/runs/17596287811/job/49989520894#step:6:158
```
0.137 go: go.mod requires go >= 1.24 (running go 1.23.12; GOTOOLCHAIN=local)
```
Fix is to get the required Go version from `go.mod` and pass the Go version to Docker as a build arg.

fix: Docker build used Go version from go.mod

---

pkgs/defang/cli.nix
src/go.mod
src/go.sum
src/pkg/cli/compose/fixup.go
src/pkg/clouds/do/appPlatform/setup.go
src/pkg/clouds/do/appPlatform/setup_test.go
src/pkg/utils.go
src/pkg/utils_test.go
src/testdata/railpack/compose.yaml
src/testdata/railpack/compose.yaml.fixup
src/testdata/railpack/compose.yaml.golden

Previous shell-quote used single quotes, which would break `$PORT` in Compose `command`, because the shell would no longer expand the env var. Now using Go's `strconv.Quote`, which uses `"`.

fix(railpack): use ShellQuote to preserve env vars in command

---

src/pkg/mcp/tools/deploy_test.go

mcp deploy_test does not override the the function to open the browser to portal. This fix will make a dummy function to for the open brower.
#1422

fix test does not open browser

---

src/pkg/mcp/tests/client_test.go
src/pkg/mcp/tools/common.go
src/pkg/mcp/tools/deploy.go
src/pkg/mcp/tools/deploy_test.go
src/pkg/mcp/tools/destroy_test.go
src/pkg/mcp/tools/listConfig_test.go
src/pkg/mcp/tools/removeConfig_test.go
src/pkg/mcp/tools/services_test.go
src/pkg/mcp/utils.go

This PR will improve the quality of the deployment response to have the expected user website domain in the response.

fix(mcp): return URLs to agent

---

src/bin/install

Added instructions to run MCP setup after installation.

Add MCP setup instruction to installation script

---

src/cmd/cli/command/commands.go
src/cmd/cli/command/mcp.go
src/pkg/mcp/setup.go
src/pkg/mcp/setup_test.go

It’s not a good UX to expect users to know and correctly spell the client they want our MCP server to connect to. Instead, we should provide a list of IDEs for them to pick from.
Also move the alias to the --client flag only.  I did keep backwards compatibility for the --client flag. 
You can also install 1 or all the clients with the picker.
#1444

Added a client picker for mcp setup command

---

src/cmd/cli/command/mcp.go
src/pkg/mcp/setup.go
src/pkg/mcp/setup_test.go

Currently, when we run `defang mcp setup`, the command attempts to write the config. One edge case I didn’t account for is when an mcp.json file already exists but is empty or just has a bunch of white spaces. Right now, we don’t overwrite it (though we should, since it’s empty). If the file exists and contains invalid JSON, we just return an error.
I also updated the messaging to tell user to update their IDE to the new version for the best experenice.
This PR will fix the mention edge case.

MCP setup bug on empty JSON file

---

src/pkg/mcp/setup.go
src/pkg/mcp/setup_test.go

This PR is suggestion on how to improve #1464 which is wrestling with the increasing complexity of reading and writing mcp config files for various clients. I observe that MCP servers are configured the same individually, but the context in which the individual server configurations live is slightly different client-to-client. This PR aims to take advantage of that observation by unifying defang mcp server configuration into a single function `configureDefangMCPServer` which accepts a path and a client. Depending on the client, configuration will be written as json or as toml, and with the appropriate top-level key.
I also note that I think it's a bad idea to try to type the config data that we are reading. I think it's wise to be as permissive as possible here since this is not our …

refactor mcp server config

---

src/pkg/mcp/tools/common.go
src/pkg/mcp/tools/tools.go

Added support for any Compose file(s). This means it will either default to compose.yaml if none is specified, accept a combination of multiple Compose files, or work with a single non-standard Compose file.
I also think the working directory should be a required requirement because we rely on it. 
Below are results of BYOC and Playground during testing the changes:
Full path non-standard compose file estimate:
non-standard compose file AWS BYOC deployment:
Two combine compose files playground deployment:
Standard compose, showing that backward compatibility is not broken:
If it cannot find/failed on the compose file it tried it will try other compose files in the working directory:
#1387

added support for different compose file(s)

---

src/pkg/mcp/tools/estimate.go
src/pkg/mcp/tools/estimate_test.go
src/pkg/mcp/tools/tools.go

change the `estimate` tool parameter schema for `deployment_mode` to include `HIGH_AVAILABILITY`(with an underscore) instead of `HIGH AVAILABILITY` (with a space). It looks like the llm ignored it and added the underscore. 🤷  Probably possible that it will add the space at some point, so we're adding an error in the default case instead of defaulting to `AFFORDABLE`.

allow HIGH_AVAILABILITY deployment_mode

---

src/pkg/clouds/gcp/account.go
src/pkg/clouds/gcp/account_test.go

Add support for authenticating with Google Cloud using Workload Identity Federation in addition to traditional service account keys. This enables GitHub Actions and other federated identity providers to authenticate without requiring service account key files.
Running our GCP deployment in CI is green now https://github.com/DefangLabs/defang-mvp/actions/runs/18230391057/job/51912103148

Support GCP Workload Identity Federation Credentials for CI

---

src/pkg/cli/client/byoc/gcp/byoc.go

Fixes: https://github.com/DefangLabs/defang-mvp/issues/2290
We should check if the error is nil again after retry of `b.driver.CreateSecret` after enabling secret manager. Currently, if it succeeds, we still report a nil error.jk
https://github.com/DefangLabs/defang-mvp/issues/2290

Check if the err of set config is nil after enable secret manager api

---

src/pkg/mcp/common/common.go
src/pkg/mcp/common/common_test.go
src/pkg/mcp/tools/common.go
src/pkg/mcp/tools/common_test.go
src/pkg/mcp/tools/deploy.go
src/pkg/mcp/tools/destroy.go
src/pkg/mcp/tools/services.go
src/pkg/mcp/tools/services_test.go

after moving TOS acceptance to login page in auth.defang.io, fabric will not return this error to authenticated users, so we don't need to give this special handling in the mcp server.

HandleTermsOfServiceError is no longer necessary
